project:
  type: website
  output-dir: docs
  resources: 
    - images/
    - data/
    - CNAME

website:
  title: ""
  favicon: "images/sabrlogo.png"
  google-analytics: "G-GGNXXW6FWM"
  navbar:
    background: "#FFFFFF"
    foreground: "#BD3039"
    logo: "images/thesabrhood2clean.png"
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Articles
      - href: leaderboards.qmd
        text: Leaderboards
      - href: glossary.qmd
        text: Stat Glossary
      - href: about.qmd
        text: About

      
format:
  html:
    css: styles.css