example_raw_pbp <- function() {
  tibble::tibble(
    game_pk = c(rep(1L, 5), rep(2L, 5)),
    game_date = c(rep("2026-07-01", 5), rep("2026-07-02", 5)),
    isPitch = TRUE,
    pitchNumber = c(1L, 2L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L),
    about.atBatIndex = c(1L, 1L, 2L, 3L, 4L, 1L, 1L, 2L, 3L, 4L),
    about.inning = c(1L, 1L, 1L, 7L, 7L, 1L, 1L, 1L, 8L, 8L),
    about.halfInning = "top",
    about.isTopInning = TRUE,
    batting_team = "NYY",
    fielding_team = "BOS",
    home_team = "BOS",
    away_team = "NYY",
    matchup.pitcher.id = c(10L, 10L, 10L, 20L, 20L, 10L, 10L, 10L, 20L, 20L),
    matchup.pitcher.fullName = c(rep("Starter One", 3), rep("Reliever One", 2), rep("Starter One", 3), rep("Reliever One", 2)),
    matchup.pitchHand.code = c(rep("R", 3), rep("L", 2), rep("R", 3), rep("L", 2)),
    matchup.batter.id = c(101L, 101L, 102L, 103L, 104L, 101L, 101L, 102L, 103L, 104L),
    matchup.batter.fullName = c("A", "A", "B", "C", "D", "A", "A", "B", "C", "D"),
    matchup.batSide.code = c("R", "R", "L", "R", "L", "R", "R", "L", "R", "L"),
    count.balls.start = 0L,
    count.strikes.start = c(0L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L),
    count.outs.start = c(0L, 0L, 1L, 0L, 1L, 0L, 0L, 1L, 0L, 1L),
    count.balls.end = 0L,
    count.strikes.end = c(1L, 2L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L),
    count.outs.end = c(0L, 1L, 2L, 1L, 1L, 0L, 1L, 2L, 1L, 1L),
    result.eventType = c("strikeout", "strikeout", "field_out", "field_out", "single", "strikeout", "strikeout", "field_out", "field_out", "single"),
    result.event = result.eventType,
    details.isInPlay = result.eventType %in% c("field_out", "single"),
    details.isStrike = TRUE,
    details.isBall = FALSE,
    details.call.description = c(
      "Called Strike", "Swinging Strike", "In play, out(s)", "In play, out(s)", "In play, no out",
      "Called Strike", "Swinging Strike", "In play, out(s)", "In play, out(s)", "In play, no out"
    ),
    last.pitch.of.ab = c(FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE),
    details.type.code = c("FF", "SL", "FF", "SI", "CH", "FF", "SL", "FF", "SI", "CH"),
    details.type.description = c("Four-Seam Fastball", "Slider", "Four-Seam Fastball", "Sinker", "Changeup", "Four-Seam Fastball", "Slider", "Four-Seam Fastball", "Sinker", "Changeup"),
    pitchData.startSpeed = c(95, 86, 94, 93, 85, 95, 86, 94, 93, 85),
    pitchData.zone = 5L,
    pitchData.coordinates.pX = seq(-0.4, 0.5, length.out = 10),
    pitchData.coordinates.pZ = seq(1.8, 3.6, length.out = 10),
    hitData.launchSpeed = ifelse(result.eventType %in% c("field_out", "single"), 90, NA_real_),
    hitData.launchAngle = ifelse(result.eventType %in% c("field_out", "single"), 12, NA_real_),
    hitData.trajectory = ifelse(result.eventType %in% c("field_out", "single"), "ground_ball", NA_character_),
    hitData.location = ifelse(result.eventType %in% c("field_out", "single"), 6L, NA_integer_),
    details.homeScore = 0L,
    details.awayScore = 0L,
    result.homeScore = 0L,
    result.awayScore = 0L,
    result.rbi = 0L
  )
}
