test_that("run expectation calibrator learns and applies a score scale", {
  set.seed(41)
  raw <- rep(seq(3.2, 5.8, length.out = 80), 2)
  home <- rep(c(FALSE, TRUE), each = 80)
  actual <- rpois(length(raw), exp(0.08 + 0.92 * log(raw) + 0.04 * as.integer(home)))
  rows <- data.frame(actual_runs = actual, raw_expected_runs = raw, is_home = home)
  model <- fit_run_expectation_calibrator(rows, min_rows = 100)
  prediction <- predict_run_expectation(model, c(4, 4), c(FALSE, TRUE))
  expect_s3_class(model, "sabrhood_run_calibrator")
  expect_length(prediction, 2)
  expect_true(all(prediction > 1.5 & prediction < 8))
  expect_gt(prediction[[2]], prediction[[1]])
})

test_that("probability scoring and calibration preserve outcome evidence", {
  probability <- c(.1, .2, .7, .8, .9)
  actual <- c(0, 0, 1, 1, 1)
  metrics <- score_projection_probabilities(probability, actual)
  calibration <- build_probability_calibration(probability, actual, bins = 5)
  expect_equal(metrics$observations, 5)
  expect_lt(metrics$brier_score, .1)
  expect_equal(sum(calibration$observations), 5)
  expect_true(all(calibration$mean_probability >= 0 & calibration$mean_probability <= 1))
})

test_that("probability calibrator shrinks overconfident forecasts", {
  set.seed(17)
  raw <- rep(seq(.1, .9, length.out = 100), 4)
  actual <- rbinom(length(raw), 1, stats::plogis(.70 * stats::qlogis(raw)))
  model <- fit_probability_calibrator(raw, actual, min_rows = 300)
  calibrated <- predict_calibrated_probability(model, c(.1, .5, .9))
  expect_s3_class(model, "sabrhood_probability_calibrator")
  expect_true(all(calibrated > 0 & calibrated < 1))
  expect_lt(calibrated[[3]], .9)
  expect_gt(calibrated[[1]], .1)
})
