<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Projections – The SABRhood</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./images/new-sabr-logo.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f0a6828d39eed76dd9f56b390c71b39b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-GGNXXW6FWM"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-GGNXXW6FWM', { 'anonymize_ip': true});
</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="theme-color" content="#0C2340">


<link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="includes/article-team-themes.css">
<meta property="og:title" content="Projections – The SABRhood">
<meta property="og:description" content="">
<meta property="og:image" content="https://thesabrhood.com/images/sabrhood-social-preview-v1.png">
<meta property="og:site_name" content="The SABRhood">
<meta property="og:image:height" content="946">
<meta property="og:image:width" content="1662">
<meta name="twitter:title" content="Projections – The SABRhood">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://thesabrhood.com/images/sabrhood-social-preview-v1.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="946">
<meta name="twitter:image-width" content="1662">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./images/thesabrhood2clean.png" alt="" class="navbar-logo light-content">
    <img src="./images/thesabrhood2clean.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">The SABRhood</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./today.html"> 
<span class="menu-text">Today</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./leaderboards.html"> 
<span class="menu-text">Leaders</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-awards" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Awards</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-awards">    
        <li>
    <a class="dropdown-item" href="./races.html">
 <span class="dropdown-text">MLB Award Races</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./insane-awards.html">
 <span class="dropdown-text">Insane Baseball Awards</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-intelligence" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Intelligence</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-intelligence">    
        <li>
    <a class="dropdown-item" href="./story-desk.html">
 <span class="dropdown-text">Story Engine</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./players.html">
 <span class="dropdown-text">Players</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./player-change-engine.html">
 <span class="dropdown-text">Player Change Engine</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./teams.html">
 <span class="dropdown-text">Teams</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./team-reports.html">
 <span class="dropdown-text">Team reports</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./matchups.html">
 <span class="dropdown-text">Matchups</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./pitch-lab.html">
 <span class="dropdown-text">Pitch Lab</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aaa.html">
 <span class="dropdown-text">Triple-A Watch</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./history.html">
 <span class="dropdown-text">History</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./league-trends.html">
 <span class="dropdown-text">League Trends</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="./projections.html" aria-current="page"> 
<span class="menu-text">Projections</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./newsletter.html"> 
<span class="menu-text">Newsletter</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./graphics-feed.html"> 
<span class="menu-text">Graphics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./blog.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./broadcast.html"> 
<span class="menu-text">Broadcast</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Projections</h1>
</div>



<div class="quarto-title-meta column-page">

    
  
    
  </div>
  


</header>


<div class="page-intro page-intro--dark">
<p><span class="eyebrow">Daily simulation center</span></p>
<section id="a-forecast-is-a-range-of-game-stories-not-one-final-score" class="level1">
<h1>A forecast is a range of game stories, not one final score</h1>
<p>The simulator turns current game inputs into transparent win probabilities, score ranges, matchup drivers, bullpen effects, and player opportunities, with uncertainty visible everywhere.</p>
</section>
</div>
<div class="projection-status-strip">
<span><strong>Scheduled-game laboratory v4</strong> Today’s slate is running in development mode</span><span>Actual starters, posted orders, active rosters, weather, empirical runner profiles, and named bullpens · calibration pending</span>
</div>
<section class="live-input-section">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Live input assembly · July 26, 2026</span>
<h2 class="anchored">
Today’s projection inputs
</h2>
<p>
BaseballR supplies the schedule, probable starters, posted orders, and active rosters. Park coordinates route each game to its Open-Meteo window, and the development simulator now consumes the resulting game rows.
</p>
</div>
<div class="method-grid">
<article class="data-card data-card--navy">
<span class="eyebrow">Schedule</span>
<h3 class="anchored">
MLB games
</h3>
<div class="data-card__value">
15
</div>
<p>
Game IDs, teams, first pitch, venue, and status.
</p>
</article>
<article class="data-card data-card--red">
<span class="eyebrow">Posted orders</span>
<h3 class="anchored">
Complete games
</h3>
<div class="data-card__value">
14/15
</div>
<p>
252 confirmed batting-order rows.
</p>
</article>
<article class="data-card data-card--steel">
<span class="eyebrow">Active roster gate</span>
<h3 class="anchored">
Verified players
</h3>
<div class="data-card__value">
780
</div>
<p>
248 workload-qualified bullpen rows remain after the roster join.
</p>
</article>
<article class="data-card data-card--navy">
<span class="eyebrow">Park weather</span>
<h3 class="anchored">
Resolved games
</h3>
<div class="data-card__value">
15/15
</div>
<p>
15 of 15 park environments resolved
</p>
</article>
</div>
<section class="dashboard-block">
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Away
</th>
<th>
Home
</th>
<th>
Away starter
</th>
<th>
Home starter
</th>
<th>
Away order
</th>
<th>
Home order
</th>
<th>
Park weather
</th>
<th>
Temp
</th>
<th>
Wind
</th>
<th>
Rain
</th>
<th>
Input state
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Cleveland Guardians
</td>
<td>
Tampa Bay Rays
</td>
<td>
Parker Messick
</td>
<td>
Drew Rasmussen
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
St.&nbsp;Petersburg, Florida
</td>
<td>
Indoor
</td>
<td>
-
</td>
<td>
-
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Arizona Diamondbacks
</td>
<td>
Washington Nationals
</td>
<td>
Kohl Drake
</td>
<td>
Miles Mikolas
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
Washington, District of Columbia
</td>
<td>
69 F
</td>
<td>
2.3 mph
</td>
<td>
0%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Chicago Cubs
</td>
<td>
Pittsburgh Pirates
</td>
<td>
Jameson Taillon
</td>
<td>
Braxton Ashcraft
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
Pittsburgh, Pennsylvania
</td>
<td>
67 F
</td>
<td>
1.7 mph
</td>
<td>
0%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Toronto Blue Jays
</td>
<td>
Boston Red Sox
</td>
<td>
Kevin Gausman
</td>
<td>
Ranger Suarez
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
Boston, Massachusetts
</td>
<td>
57 F
</td>
<td>
3.5 mph
</td>
<td>
0%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Atlanta Braves
</td>
<td>
Baltimore Orioles
</td>
<td>
Reynaldo López
</td>
<td>
Shane Baz
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
Baltimore, Maryland
</td>
<td>
68 F
</td>
<td>
3.3 mph
</td>
<td>
1%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Kansas City Royals
</td>
<td>
Detroit Tigers
</td>
<td>
Luinder Avila
</td>
<td>
Framber Valdez
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
Detroit, Michigan
</td>
<td>
67 F
</td>
<td>
4.2 mph
</td>
<td>
0%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Los Angeles Dodgers
</td>
<td>
New York Mets
</td>
<td>
Emmet Sheehan
</td>
<td>
Freddy Peralta
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
Queens, New York
</td>
<td>
63 F
</td>
<td>
3.5 mph
</td>
<td>
0%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
San Diego Padres
</td>
<td>
Miami Marlins
</td>
<td>
Walker Buehler
</td>
<td>
Janson Junk
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
Miami, Florida
</td>
<td>
80 F
</td>
<td>
2.8 mph
</td>
<td>
4%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Athletics
</td>
<td>
Minnesota Twins
</td>
<td>
Jeffrey Springs
</td>
<td>
Connor Prielipp
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
Minneapolis, Minnesota
</td>
<td>
75 F
</td>
<td>
3.6 mph
</td>
<td>
32%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Houston Astros
</td>
<td>
Chicago White Sox
</td>
<td>
Ronel Blanco
</td>
<td>
Erick Fedde
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
Chicago, Illinois
</td>
<td>
70 F
</td>
<td>
5.3 mph
</td>
<td>
1%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Colorado Rockies
</td>
<td>
Milwaukee Brewers
</td>
<td>
Kyle Freeland
</td>
<td>
Jacob Misiorowski
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
Milwaukee, Wisconsin
</td>
<td>
74 F
</td>
<td>
5.6 mph
</td>
<td>
5%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Cincinnati Reds
</td>
<td>
St.&nbsp;Louis Cardinals
</td>
<td>
Andrew Abbott
</td>
<td>
Kyle Leahy
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
St.&nbsp;Louis, Missouri
</td>
<td>
79 F
</td>
<td>
2.9 mph
</td>
<td>
0%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Seattle Mariners
</td>
<td>
Texas Rangers
</td>
<td>
Logan Gilbert
</td>
<td>
Jacob deGrom
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
Arlington, Texas
</td>
<td>
85 F
</td>
<td>
9.4 mph
</td>
<td>
0%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
Los Angeles Angels
</td>
<td>
San Francisco Giants
</td>
<td>
José Soriano
</td>
<td>
Carson Whisenhunt
</td>
<td>
confirmed
</td>
<td>
confirmed
</td>
<td>
San Francisco, California
</td>
<td>
56 F
</td>
<td>
4.9 mph
</td>
<td>
0%
</td>
<td>
ready
</td>
</tr>
<tr>
<td>
New York Yankees
</td>
<td>
Philadelphia Phillies
</td>
<td>
Will Warren
</td>
<td>
Cristopher Sánchez
</td>
<td>
missing
</td>
<td>
missing
</td>
<td>
Philadelphia, Pennsylvania
</td>
<td>
64 F
</td>
<td>
2.8 mph
</td>
<td>
0%
</td>
<td>
conditional
</td>
</tr>
</tbody>
</table>
</div>
</section>
<div class="method-callout">
<strong>Current boundary:</strong> a resolved input row is not the same as a validated forecast. Starter, lineup, active-roster bullpen, and temperature effects now enter the score model; park factors, fresh reliever workload, and out-of-time calibration remain open gates.
</div>
</section>
<section class="projection-matchup-lab">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Simulation Phase 1 · shadow model</span>
<h2 class="anchored">
Every confirmed hitter now has a starter-specific event distribution
</h2>
<p>
The new layer combines batter and pitcher results with multinomial log5, shrinks small samples, applies the appropriate handedness splits, and makes restrained recent-form adjustments. These probabilities are being audited beside the current simulator before they are allowed to drive it.
</p>
</div>
<div class="method-grid">
<article class="data-card data-card--navy">
<span class="eyebrow">Matchup coverage</span>
<h3 class="anchored">
Confirmed rows
</h3>
<div class="data-card__value">
252
</div>
<p>
14 games
</p>
</article>
<article class="data-card data-card--steel">
<span class="eyebrow">Handedness</span>
<h3 class="anchored">
Complete splits
</h3>
<div class="data-card__value">
77.0%
</div>
<p>
Both the hitter and starter have the required split.
</p>
</article>
<article class="data-card data-card--red">
<span class="eyebrow">Reliability</span>
<h3 class="anchored">
Average score
</h3>
<div class="data-card__value">
52.0
</div>
<p>
Overall and split sample sizes determine the visible confidence.
</p>
</article>
</div>
<section class="dashboard-block">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Highest modeled production against today’s starter</span>
<h3 class="anchored">
The probability components remain visible
</h3>
<p>
A strong matchup can come from contact, power, patience, or avoiding strikeouts. Reliability is shown so an extreme number cannot hide its sample quality.
</p>
</div>
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Hitter
</th>
<th>
Team
</th>
<th>
Starter
</th>
<th>
Bat
</th>
<th>
Throws
</th>
<th>
K
</th>
<th>
BB
</th>
<th>
Hit
</th>
<th>
HR
</th>
<th>
Est. wOBA
</th>
<th>
Reliability
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Andrew Vaughn
</td>
<td>
Milwaukee Brewers
</td>
<td>
Kyle Freeland
</td>
<td>
R
</td>
<td>
L
</td>
<td>
11.7%
</td>
<td>
7.5%
</td>
<td>
36.3%
</td>
<td>
3.2%
</td>
<td>
0.480
</td>
<td>
55.6
</td>
</tr>
<tr>
<td>
Yordan Alvarez
</td>
<td>
Houston Astros
</td>
<td>
Erick Fedde
</td>
<td>
L
</td>
<td>
R
</td>
<td>
13.9%
</td>
<td>
14.0%
</td>
<td>
28.8%
</td>
<td>
5.9%
</td>
<td>
0.438
</td>
<td>
66.2
</td>
</tr>
<tr>
<td>
Brandon Lowe
</td>
<td>
Pittsburgh Pirates
</td>
<td>
Jameson Taillon
</td>
<td>
L
</td>
<td>
R
</td>
<td>
22.6%
</td>
<td>
11.1%
</td>
<td>
24.3%
</td>
<td>
11.1%
</td>
<td>
0.435
</td>
<td>
62.1
</td>
</tr>
<tr>
<td>
Gary Sánchez
</td>
<td>
Milwaukee Brewers
</td>
<td>
Kyle Freeland
</td>
<td>
R
</td>
<td>
L
</td>
<td>
15.9%
</td>
<td>
10.8%
</td>
<td>
28.5%
</td>
<td>
6.3%
</td>
<td>
0.432
</td>
<td>
55.4
</td>
</tr>
<tr>
<td>
Jackson Chourio
</td>
<td>
Milwaukee Brewers
</td>
<td>
Kyle Freeland
</td>
<td>
R
</td>
<td>
L
</td>
<td>
20.7%
</td>
<td>
5.6%
</td>
<td>
32.6%
</td>
<td>
6.6%
</td>
<td>
0.428
</td>
<td>
60.5
</td>
</tr>
<tr>
<td>
Ryan O’Hearn
</td>
<td>
Pittsburgh Pirates
</td>
<td>
Jameson Taillon
</td>
<td>
L
</td>
<td>
R
</td>
<td>
21.3%
</td>
<td>
9.5%
</td>
<td>
26.7%
</td>
<td>
9.5%
</td>
<td>
0.422
</td>
<td>
60.5
</td>
</tr>
<tr>
<td>
Freddie Freeman
</td>
<td>
Los Angeles Dodgers
</td>
<td>
Freddy Peralta
</td>
<td>
L
</td>
<td>
R
</td>
<td>
16.7%
</td>
<td>
11.2%
</td>
<td>
29.3%
</td>
<td>
4.3%
</td>
<td>
0.417
</td>
<td>
68.7
</td>
</tr>
<tr>
<td>
Byron Buxton
</td>
<td>
Minnesota Twins
</td>
<td>
Jeffrey Springs
</td>
<td>
R
</td>
<td>
L
</td>
<td>
21.3%
</td>
<td>
5.8%
</td>
<td>
28.0%
</td>
<td>
9.5%
</td>
<td>
0.416
</td>
<td>
62.3
</td>
</tr>
<tr>
<td>
Esmerlyn Valdez
</td>
<td>
Pittsburgh Pirates
</td>
<td>
Jameson Taillon
</td>
<td>
R
</td>
<td>
R
</td>
<td>
34.9%
</td>
<td>
7.4%
</td>
<td>
25.8%
</td>
<td>
10.9%
</td>
<td>
0.415
</td>
<td>
48.0
</td>
</tr>
<tr>
<td>
Ryan Jeffers
</td>
<td>
Minnesota Twins
</td>
<td>
Jeffrey Springs
</td>
<td>
R
</td>
<td>
L
</td>
<td>
14.9%
</td>
<td>
12.8%
</td>
<td>
25.7%
</td>
<td>
6.9%
</td>
<td>
0.414
</td>
<td>
55.4
</td>
</tr>
<tr>
<td>
Pete Crow-Armstrong
</td>
<td>
Chicago Cubs
</td>
<td>
Braxton Ashcraft
</td>
<td>
L
</td>
<td>
R
</td>
<td>
32.3%
</td>
<td>
8.2%
</td>
<td>
26.0%
</td>
<td>
7.2%
</td>
<td>
0.406
</td>
<td>
68.4
</td>
</tr>
<tr>
<td>
Dillon Dingler
</td>
<td>
Detroit Tigers
</td>
<td>
Luinder Avila
</td>
<td>
R
</td>
<td>
R
</td>
<td>
19.7%
</td>
<td>
9.5%
</td>
<td>
25.0%
</td>
<td>
5.2%
</td>
<td>
0.402
</td>
<td>
58.9
</td>
</tr>
</tbody>
</table>
</div>
</section>
<div class="method-callout">
<strong>Probability contract:</strong> walk, hit-by-pitch, strikeout, single, double, triple, home run, and other out are mutually exclusive. The maximum sum error in today’s 252 rows is 2.220446e-16.
</div>
</section>
<section class="projection-state-lab">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Simulation Phase 4 · empirical running game</span>
<h2 class="anchored">
Runner identity, park movement, and pitcher hold now change each game path
</h2>
<p>
Every draw maintains inning, outs, named runners, score, batting-order position, pitcher identity, workload, and available bullpen arms. Phase 4 replaces generic running assumptions with league-shrunk player tendencies, an empirical venue layer, and pitcher-specific attempt suppression.
</p>
</div>
<div class="method-grid">
<article class="data-card data-card--navy">
<span class="eyebrow">Detailed slate</span>
<h3 class="anchored">
Games simulated
</h3>
<div class="data-card__value">
14
</div>
<p>
250 shadow draws per game
</p>
</article>
<article class="data-card data-card--steel">
<span class="eyebrow">Bullpen path</span>
<h3 class="anchored">
Named arms used
</h3>
<div class="data-card__value">
9.0
</div>
<p>
41.8% of plate appearances
</p>
</article>
<article class="data-card data-card--red">
<span class="eyebrow">Ball in play</span>
<h3 class="anchored">
Double plays
</h3>
<div class="data-card__value">
1.25
</div>
<p>
0.77 runs per game from productive outs
</p>
</article>
<article class="data-card data-card--navy">
<span class="eyebrow">Running game</span>
<h3 class="anchored">
Steal attempts
</h3>
<div class="data-card__value">
0.43
</div>
<p>
0.38 successful steals per game
</p>
</article>
<article class="data-card data-card--steel">
<span class="eyebrow">Historical foundation</span>
<h3 class="anchored">
Runner windows
</h3>
<div class="data-card__value">
89,642
</div>
<p>
1,570 completed games
</p>
</article>
<article class="data-card data-card--red">
<span class="eyebrow">Profile coverage</span>
<h3 class="anchored">
Today’s hitters
</h3>
<div class="data-card__value">
99.6%
</div>
<p>
Missing players fall back to the league prior.
</p>
</article>
</div>
<section class="dashboard-block">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Phase 4 shadow game board</span>
<h3 class="anchored">
Sequencing, parks, bullpen decisions, and runner traits shape the score
</h3>
<p>
Starter BF, bullpen share, relievers used, double plays, steals, and empirical park advancement all come from the same simulation.
</p>
</div>
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Away
</th>
<th>
Home
</th>
<th>
Away win
</th>
<th>
Home win
</th>
<th>
Away runs
</th>
<th>
Home runs
</th>
<th>
One-run
</th>
<th>
Away SP BF
</th>
<th>
Home SP BF
</th>
<th>
Relievers
</th>
<th>
DP
</th>
<th>
SB
</th>
<th>
Park path
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Toronto Blue Jays
</td>
<td>
Boston Red Sox
</td>
<td>
42.4%
</td>
<td>
57.2%
</td>
<td>
3.3
</td>
<td>
3.5
</td>
<td>
40.0%
</td>
<td>
22.4
</td>
<td>
21.4
</td>
<td>
8.7
</td>
<td>
1.23
</td>
<td>
0.22
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
San Diego Padres
</td>
<td>
Miami Marlins
</td>
<td>
45.2%
</td>
<td>
54.8%
</td>
<td>
4.4
</td>
<td>
4.5
</td>
<td>
36.4%
</td>
<td>
20.4
</td>
<td>
22.1
</td>
<td>
9.5
</td>
<td>
1.27
</td>
<td>
0.47
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Cleveland Guardians
</td>
<td>
Tampa Bay Rays
</td>
<td>
50.8%
</td>
<td>
49.2%
</td>
<td>
3.6
</td>
<td>
3.4
</td>
<td>
36.4%
</td>
<td>
22.2
</td>
<td>
21.4
</td>
<td>
8.7
</td>
<td>
1.32
</td>
<td>
0.58
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Los Angeles Angels
</td>
<td>
San Francisco Giants
</td>
<td>
55.2%
</td>
<td>
44.8%
</td>
<td>
4.3
</td>
<td>
3.4
</td>
<td>
35.6%
</td>
<td>
22.4
</td>
<td>
21.8
</td>
<td>
9.0
</td>
<td>
1.23
</td>
<td>
0.20
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Atlanta Braves
</td>
<td>
Baltimore Orioles
</td>
<td>
52.8%
</td>
<td>
46.8%
</td>
<td>
4.6
</td>
<td>
4.2
</td>
<td>
33.6%
</td>
<td>
23.0
</td>
<td>
23.3
</td>
<td>
8.8
</td>
<td>
1.20
</td>
<td>
0.26
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Seattle Mariners
</td>
<td>
Texas Rangers
</td>
<td>
52.4%
</td>
<td>
47.6%
</td>
<td>
3.7
</td>
<td>
3.4
</td>
<td>
33.2%
</td>
<td>
22.2
</td>
<td>
21.4
</td>
<td>
8.6
</td>
<td>
1.16
</td>
<td>
0.34
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Athletics
</td>
<td>
Minnesota Twins
</td>
<td>
35.2%
</td>
<td>
64.8%
</td>
<td>
3.8
</td>
<td>
5.3
</td>
<td>
33.2%
</td>
<td>
21.6
</td>
<td>
21.4
</td>
<td>
9.1
</td>
<td>
1.25
</td>
<td>
0.50
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Cincinnati Reds
</td>
<td>
St.&nbsp;Louis Cardinals
</td>
<td>
46.8%
</td>
<td>
53.2%
</td>
<td>
3.8
</td>
<td>
3.9
</td>
<td>
32.8%
</td>
<td>
22.1
</td>
<td>
20.8
</td>
<td>
9.2
</td>
<td>
1.35
</td>
<td>
0.36
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Los Angeles Dodgers
</td>
<td>
New York Mets
</td>
<td>
64.8%
</td>
<td>
35.2%
</td>
<td>
5.2
</td>
<td>
3.5
</td>
<td>
31.6%
</td>
<td>
20.4
</td>
<td>
22.0
</td>
<td>
9.5
</td>
<td>
1.25
</td>
<td>
0.28
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Arizona Diamondbacks
</td>
<td>
Washington Nationals
</td>
<td>
57.2%
</td>
<td>
42.8%
</td>
<td>
4.7
</td>
<td>
3.8
</td>
<td>
30.0%
</td>
<td>
20.6
</td>
<td>
24.2
</td>
<td>
8.6
</td>
<td>
1.28
</td>
<td>
0.45
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Houston Astros
</td>
<td>
Chicago White Sox
</td>
<td>
53.6%
</td>
<td>
46.4%
</td>
<td>
4.8
</td>
<td>
3.9
</td>
<td>
29.6%
</td>
<td>
19.0
</td>
<td>
23.9
</td>
<td>
9.2
</td>
<td>
1.36
</td>
<td>
0.29
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Colorado Rockies
</td>
<td>
Milwaukee Brewers
</td>
<td>
26.8%
</td>
<td>
73.2%
</td>
<td>
3.2
</td>
<td>
5.3
</td>
<td>
28.4%
</td>
<td>
22.5
</td>
<td>
21.3
</td>
<td>
8.5
</td>
<td>
1.08
</td>
<td>
0.40
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Kansas City Royals
</td>
<td>
Detroit Tigers
</td>
<td>
40.0%
</td>
<td>
60.0%
</td>
<td>
4.2
</td>
<td>
4.8
</td>
<td>
27.6%
</td>
<td>
23.4
</td>
<td>
22.4
</td>
<td>
9.0
</td>
<td>
1.38
</td>
<td>
0.40
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
<tr>
<td>
Chicago Cubs
</td>
<td>
Pittsburgh Pirates
</td>
<td>
38.8%
</td>
<td>
61.2%
</td>
<td>
4.3
</td>
<td>
5.4
</td>
<td>
25.6%
</td>
<td>
21.4
</td>
<td>
22.1
</td>
<td>
9.2
</td>
<td>
1.09
</td>
<td>
0.54
</td>
<td>
empirical_shrunk_2026
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="dashboard-block phase4-running-room">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Running-game intelligence</span>
<h3 class="anchored">
Who creates pressure, who suppresses it, and where does the outfield change the route?
</h3>
<p>
Attempt rates use every eligible runner window. Success and advancement rates are shrunk toward league context so a handful of plays cannot masquerade as a stable skill.
</p>
</div>
<div class="projection-phase4-grid">
<div>
<h4 class="anchored">
Today’s most aggressive runners
</h4>
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Runner
</th>
<th>
Windows
</th>
<th>
Attempts
</th>
<th>
Attempt rate
</th>
<th>
Success
</th>
<th>
Reliability
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Cedric Mullins
</td>
<td>
76
</td>
<td>
9
</td>
<td>
8.8%
</td>
<td>
84.8%
</td>
<td>
68.5%
</td>
</tr>
<tr>
<td>
Esteury Ruiz
</td>
<td>
34
</td>
<td>
5
</td>
<td>
8.3%
</td>
<td>
90.8%
</td>
<td>
49.3%
</td>
</tr>
<tr>
<td>
José Ramírez
</td>
<td>
83
</td>
<td>
8
</td>
<td>
7.4%
</td>
<td>
88.0%
</td>
<td>
70.3%
</td>
</tr>
<tr>
<td>
Pete Crow-Armstrong
</td>
<td>
111
</td>
<td>
10
</td>
<td>
7.4%
</td>
<td>
92.5%
</td>
<td>
76.0%
</td>
</tr>
<tr>
<td>
Elly De La Cruz
</td>
<td>
111
</td>
<td>
8
</td>
<td>
6.0%
</td>
<td>
91.9%
</td>
<td>
76.0%
</td>
</tr>
<tr>
<td>
Petey Halpin
</td>
<td>
12
</td>
<td>
2
</td>
<td>
5.8%
</td>
<td>
89.5%
</td>
<td>
25.5%
</td>
</tr>
<tr>
<td>
Jake McCarthy
</td>
<td>
82
</td>
<td>
6
</td>
<td>
5.8%
</td>
<td>
91.2%
</td>
<td>
70.1%
</td>
</tr>
<tr>
<td>
Angel Martínez
</td>
<td>
50
</td>
<td>
4
</td>
<td>
5.6%
</td>
<td>
85.9%
</td>
<td>
58.8%
</td>
</tr>
<tr>
<td>
Joey Ortiz
</td>
<td>
70
</td>
<td>
5
</td>
<td>
5.5%
</td>
<td>
86.5%
</td>
<td>
66.7%
</td>
</tr>
<tr>
<td>
Nasim Nuñez
</td>
<td>
130
</td>
<td>
8
</td>
<td>
5.3%
</td>
<td>
91.9%
</td>
<td>
78.8%
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div>
<h4 class="anchored">
Probable-starter hold profile
</h4>
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Pitcher
</th>
<th>
Team
</th>
<th>
Windows
</th>
<th>
Attempts
</th>
<th>
Attempt index
</th>
<th>
Success allowed
</th>
<th>
Reliability
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Freddy Peralta
</td>
<td>
New York Mets
</td>
<td>
145
</td>
<td>
0
</td>
<td>
29
</td>
<td>
88.3%
</td>
<td>
70.7%
</td>
</tr>
<tr>
<td>
Jeffrey Springs
</td>
<td>
Athletics
</td>
<td>
137
</td>
<td>
0
</td>
<td>
30
</td>
<td>
88.3%
</td>
<td>
69.5%
</td>
</tr>
<tr>
<td>
Parker Messick
</td>
<td>
Cleveland Guardians
</td>
<td>
124
</td>
<td>
0
</td>
<td>
33
</td>
<td>
88.3%
</td>
<td>
67.4%
</td>
</tr>
<tr>
<td>
José Soriano
</td>
<td>
Los Angeles Angels
</td>
<td>
162
</td>
<td>
1
</td>
<td>
48
</td>
<td>
83.6%
</td>
<td>
73.0%
</td>
</tr>
<tr>
<td>
Shane Baz
</td>
<td>
Baltimore Orioles
</td>
<td>
128
</td>
<td>
1
</td>
<td>
57
</td>
<td>
88.9%
</td>
<td>
68.1%
</td>
</tr>
<tr>
<td>
Jacob deGrom
</td>
<td>
Texas Rangers
</td>
<td>
119
</td>
<td>
1
</td>
<td>
60
</td>
<td>
83.6%
</td>
<td>
66.5%
</td>
</tr>
<tr>
<td>
Jacob Misiorowski
</td>
<td>
Milwaukee Brewers
</td>
<td>
99
</td>
<td>
1
</td>
<td>
67
</td>
<td>
88.9%
</td>
<td>
62.3%
</td>
</tr>
<tr>
<td>
Kevin Gausman
</td>
<td>
Toronto Blue Jays
</td>
<td>
161
</td>
<td>
2
</td>
<td>
70
</td>
<td>
89.5%
</td>
<td>
72.9%
</td>
</tr>
<tr>
<td>
Emmet Sheehan
</td>
<td>
Los Angeles Dodgers
</td>
<td>
93
</td>
<td>
1
</td>
<td>
70
</td>
<td>
88.9%
</td>
<td>
60.8%
</td>
</tr>
<tr>
<td>
Luinder Avila
</td>
<td>
Kansas City Royals
</td>
<td>
86
</td>
<td>
1
</td>
<td>
73
</td>
<td>
88.9%
</td>
<td>
58.9%
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div>
<h4 class="anchored">
Today’s strongest empirical park movement signals
</h4>
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Venue
</th>
<th>
Runner event
</th>
<th>
Opps
</th>
<th>
Observed
</th>
<th>
League
</th>
<th>
Multiplier
</th>
<th>
Reliability
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Comerica Park
</td>
<td>
single_first_to_third
</td>
<td>
205
</td>
<td>
40.5%
</td>
<td>
30.0%
</td>
<td>
115 index
</td>
<td>
53.2%
</td>
</tr>
<tr>
<td>
Fenway Park
</td>
<td>
double_first_scores
</td>
<td>
84
</td>
<td>
21.4%
</td>
<td>
34.3%
</td>
<td>
88 index
</td>
<td>
31.8%
</td>
</tr>
<tr>
<td>
Nationals Park
</td>
<td>
single_first_to_third
</td>
<td>
225
</td>
<td>
35.6%
</td>
<td>
30.0%
</td>
<td>
110 index
</td>
<td>
55.6%
</td>
</tr>
<tr>
<td>
Busch Stadium
</td>
<td>
double_first_scores
</td>
<td>
59
</td>
<td>
47.5%
</td>
<td>
34.3%
</td>
<td>
109 index
</td>
<td>
24.7%
</td>
</tr>
<tr>
<td>
Oracle Park
</td>
<td>
single_first_to_third
</td>
<td>
205
</td>
<td>
35.1%
</td>
<td>
30.0%
</td>
<td>
109 index
</td>
<td>
53.2%
</td>
</tr>
<tr>
<td>
Citizens Bank Park
</td>
<td>
single_first_to_third
</td>
<td>
259
</td>
<td>
25.9%
</td>
<td>
30.0%
</td>
<td>
92 index
</td>
<td>
59.0%
</td>
</tr>
<tr>
<td>
Oriole Park at Camden Yards
</td>
<td>
single_first_to_third
</td>
<td>
238
</td>
<td>
26.5%
</td>
<td>
30.0%
</td>
<td>
93 index
</td>
<td>
56.9%
</td>
</tr>
<tr>
<td>
Globe Life Field
</td>
<td>
single_second_scores
</td>
<td>
94
</td>
<td>
68.1%
</td>
<td>
57.4%
</td>
<td>
106 index
</td>
<td>
34.3%
</td>
</tr>
<tr>
<td>
Comerica Park
</td>
<td>
double_first_scores
</td>
<td>
50
</td>
<td>
44.0%
</td>
<td>
34.3%
</td>
<td>
106 index
</td>
<td>
21.7%
</td>
</tr>
<tr>
<td>
Fenway Park
</td>
<td>
single_first_to_third
</td>
<td>
210
</td>
<td>
26.7%
</td>
<td>
30.0%
</td>
<td>
94 index
</td>
<td>
53.8%
</td>
</tr>
<tr>
<td>
Globe Life Field
</td>
<td>
single_first_to_third
</td>
<td>
173
</td>
<td>
33.5%
</td>
<td>
30.0%
</td>
<td>
106 index
</td>
<td>
49.0%
</td>
</tr>
<tr>
<td>
Oriole Park at Camden Yards
</td>
<td>
double_first_scores
</td>
<td>
71
</td>
<td>
40.8%
</td>
<td>
34.3%
</td>
<td>
105 index
</td>
<td>
28.3%
</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section class="dashboard-block">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Manager likelihood board</span>
<h3 class="anchored">
Who is most likely to enter, and when?
</h3>
<p>
Appearance probability is produced across complete games. Selection likelihood is the arm’s average probability whenever that reliever was still available at a decision point.
</p>
</div>
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Reliever
</th>
<th>
Team
</th>
<th>
Opponent
</th>
<th>
Throws
</th>
<th>
Available
</th>
<th>
Appearance
</th>
<th>
At decision
</th>
<th>
BF / app.
</th>
<th>
Entry inn.
</th>
<th>
High leverage
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Luke Weaver
</td>
<td>
New York Mets
</td>
<td>
Los Angeles Dodgers
</td>
<td>
R
</td>
<td>
100.0%
</td>
<td>
98.8%
</td>
<td>
56.5%
</td>
<td>
3.5
</td>
<td>
6.1
</td>
<td>
28.7%
</td>
</tr>
<tr>
<td>
Ty Madden
</td>
<td>
Detroit Tigers
</td>
<td>
Kansas City Royals
</td>
<td>
R
</td>
<td>
100.0%
</td>
<td>
98.8%
</td>
<td>
52.1%
</td>
<td>
3.8
</td>
<td>
6.5
</td>
<td>
31.2%
</td>
</tr>
<tr>
<td>
Sean Newcomb
</td>
<td>
Chicago White Sox
</td>
<td>
Houston Astros
</td>
<td>
L
</td>
<td>
100.0%
</td>
<td>
98.0%
</td>
<td>
52.5%
</td>
<td>
3.6
</td>
<td>
6.9
</td>
<td>
40.8%
</td>
</tr>
<tr>
<td>
JT Brubaker
</td>
<td>
San Francisco Giants
</td>
<td>
Los Angeles Angels
</td>
<td>
R
</td>
<td>
100.0%
</td>
<td>
98.0%
</td>
<td>
43.7%
</td>
<td>
3.6
</td>
<td>
6.8
</td>
<td>
46.5%
</td>
</tr>
<tr>
<td>
Gordon Graceffo
</td>
<td>
St.&nbsp;Louis Cardinals
</td>
<td>
Cincinnati Reds
</td>
<td>
R
</td>
<td>
83.3%
</td>
<td>
98.0%
</td>
<td>
42.4%
</td>
<td>
3.6
</td>
<td>
6.8
</td>
<td>
44.1%
</td>
</tr>
<tr>
<td>
Trevor Megill
</td>
<td>
Milwaukee Brewers
</td>
<td>
Colorado Rockies
</td>
<td>
R
</td>
<td>
92.2%
</td>
<td>
97.6%
</td>
<td>
54.8%
</td>
<td>
3.5
</td>
<td>
6.8
</td>
<td>
36.1%
</td>
</tr>
<tr>
<td>
Ryan Rolison
</td>
<td>
Chicago Cubs
</td>
<td>
Pittsburgh Pirates
</td>
<td>
L
</td>
<td>
93.3%
</td>
<td>
97.6%
</td>
<td>
50.7%
</td>
<td>
3.6
</td>
<td>
6.3
</td>
<td>
27.9%
</td>
</tr>
<tr>
<td>
Keaton Winn
</td>
<td>
San Francisco Giants
</td>
<td>
Los Angeles Angels
</td>
<td>
R
</td>
<td>
90.6%
</td>
<td>
97.6%
</td>
<td>
47.1%
</td>
<td>
3.6
</td>
<td>
6.7
</td>
<td>
46.3%
</td>
</tr>
<tr>
<td>
Huascar Brazobán
</td>
<td>
New York Mets
</td>
<td>
Los Angeles Dodgers
</td>
<td>
R
</td>
<td>
91.1%
</td>
<td>
97.6%
</td>
<td>
44.9%
</td>
<td>
3.6
</td>
<td>
6.5
</td>
<td>
40.2%
</td>
</tr>
<tr>
<td>
Yennier Cano
</td>
<td>
Baltimore Orioles
</td>
<td>
Atlanta Braves
</td>
<td>
R
</td>
<td>
94.4%
</td>
<td>
96.8%
</td>
<td>
50.2%
</td>
<td>
3.4
</td>
<td>
6.7
</td>
<td>
43.4%
</td>
</tr>
<tr>
<td>
Riley O’Brien
</td>
<td>
St.&nbsp;Louis Cardinals
</td>
<td>
Cincinnati Reds
</td>
<td>
R
</td>
<td>
85.6%
</td>
<td>
96.4%
</td>
<td>
42.9%
</td>
<td>
3.8
</td>
<td>
6.7
</td>
<td>
40.7%
</td>
</tr>
<tr>
<td>
Daniel Lynch IV
</td>
<td>
Kansas City Royals
</td>
<td>
Detroit Tigers
</td>
<td>
L
</td>
<td>
93.9%
</td>
<td>
96.0%
</td>
<td>
49.6%
</td>
<td>
3.6
</td>
<td>
6.4
</td>
<td>
33.3%
</td>
</tr>
<tr>
<td>
Brennan Bernardino
</td>
<td>
Colorado Rockies
</td>
<td>
Milwaukee Brewers
</td>
<td>
L
</td>
<td>
93.9%
</td>
<td>
96.0%
</td>
<td>
49.1%
</td>
<td>
3.7
</td>
<td>
6.4
</td>
<td>
33.8%
</td>
</tr>
<tr>
<td>
Colin Holderman
</td>
<td>
Cleveland Guardians
</td>
<td>
Tampa Bay Rays
</td>
<td>
R
</td>
<td>
88.3%
</td>
<td>
95.2%
</td>
<td>
56.4%
</td>
<td>
3.5
</td>
<td>
6.7
</td>
<td>
46.6%
</td>
</tr>
<tr>
<td>
Alex Vesia
</td>
<td>
Los Angeles Dodgers
</td>
<td>
New York Mets
</td>
<td>
L
</td>
<td>
100.0%
</td>
<td>
95.2%
</td>
<td>
45.3%
</td>
<td>
3.7
</td>
<td>
6.5
</td>
<td>
29.8%
</td>
</tr>
<tr>
<td>
Mason Miller
</td>
<td>
San Diego Padres
</td>
<td>
Miami Marlins
</td>
<td>
R
</td>
<td>
63.6%
</td>
<td>
95.2%
</td>
<td>
43.4%
</td>
<td>
3.6
</td>
<td>
6.2
</td>
<td>
33.2%
</td>
</tr>
<tr>
<td>
Taylor Clarke
</td>
<td>
Arizona Diamondbacks
</td>
<td>
Washington Nationals
</td>
<td>
R
</td>
<td>
96.7%
</td>
<td>
95.2%
</td>
<td>
39.5%
</td>
<td>
3.6
</td>
<td>
6.8
</td>
<td>
38.2%
</td>
</tr>
<tr>
<td>
Nate Pearson
</td>
<td>
Houston Astros
</td>
<td>
Chicago White Sox
</td>
<td>
R
</td>
<td>
100.0%
</td>
<td>
94.8%
</td>
<td>
38.4%
</td>
<td>
3.6
</td>
<td>
6.5
</td>
<td>
33.8%
</td>
</tr>
<tr>
<td>
Clayton Beeter
</td>
<td>
Washington Nationals
</td>
<td>
Arizona Diamondbacks
</td>
<td>
R
</td>
<td>
100.0%
</td>
<td>
94.4%
</td>
<td>
53.1%
</td>
<td>
3.5
</td>
<td>
7.1
</td>
<td>
51.7%
</td>
</tr>
<tr>
<td>
Bryan Baker
</td>
<td>
Tampa Bay Rays
</td>
<td>
Cleveland Guardians
</td>
<td>
R
</td>
<td>
95.0%
</td>
<td>
94.4%
</td>
<td>
45.0%
</td>
<td>
3.5
</td>
<td>
6.8
</td>
<td>
50.8%
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="dashboard-block">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Expanded player outcomes</span>
<h3 class="anchored">
Runs, RBI, steals, sacrifice flies, and double-play risk now retain player identity
</h3>
<p>
Each occupied base stores the lineup spot that owns the runner, allowing advancement and outs to return to the appropriate player line.
</p>
</div>
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Hitter
</th>
<th>
Team
</th>
<th>
Order
</th>
<th>
PA
</th>
<th>
H
</th>
<th>
HR
</th>
<th>
R
</th>
<th>
RBI
</th>
<th>
SB
</th>
<th>
SF
</th>
<th>
GDP
</th>
<th>
1+ H
</th>
<th>
1+ HR
</th>
<th>
1+ R
</th>
<th>
1+ RBI
</th>
<th>
1+ SB
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Byron Buxton
</td>
<td>
Minnesota Twins
</td>
<td>
2
</td>
<td>
4.51
</td>
<td>
1.27
</td>
<td>
0.39
</td>
<td>
0.74
</td>
<td>
0.88
</td>
<td>
0.03
</td>
<td>
0.02
</td>
<td>
0.07
</td>
<td>
76.4%
</td>
<td>
34.0%
</td>
<td>
56.4%
</td>
<td>
46.8%
</td>
<td>
2.8%
</td>
</tr>
<tr>
<td>
Esmerlyn Valdez
</td>
<td>
Pittsburgh Pirates
</td>
<td>
4
</td>
<td>
4.28
</td>
<td>
1.05
</td>
<td>
0.38
</td>
<td>
0.75
</td>
<td>
0.94
</td>
<td>
0.01
</td>
<td>
0.04
</td>
<td>
0.07
</td>
<td>
70.8%
</td>
<td>
34.0%
</td>
<td>
58.0%
</td>
<td>
47.6%
</td>
<td>
0.8%
</td>
</tr>
<tr>
<td>
Brandon Lowe
</td>
<td>
Pittsburgh Pirates
</td>
<td>
2
</td>
<td>
4.48
</td>
<td>
1.13
</td>
<td>
0.39
</td>
<td>
0.82
</td>
<td>
0.76
</td>
<td>
0.01
</td>
<td>
0.04
</td>
<td>
0.08
</td>
<td>
70.4%
</td>
<td>
33.2%
</td>
<td>
59.2%
</td>
<td>
43.6%
</td>
<td>
1.2%
</td>
</tr>
<tr>
<td>
Yordan Alvarez
</td>
<td>
Houston Astros
</td>
<td>
2
</td>
<td>
4.69
</td>
<td>
1.31
</td>
<td>
0.30
</td>
<td>
0.71
</td>
<td>
0.76
</td>
<td>
0.00
</td>
<td>
0.02
</td>
<td>
0.06
</td>
<td>
76.4%
</td>
<td>
29.6%
</td>
<td>
54.0%
</td>
<td>
44.8%
</td>
<td>
0.4%
</td>
</tr>
<tr>
<td>
Kody Clemens
</td>
<td>
Minnesota Twins
</td>
<td>
5
</td>
<td>
4.19
</td>
<td>
1.00
</td>
<td>
0.28
</td>
<td>
0.61
</td>
<td>
0.81
</td>
<td>
0.02
</td>
<td>
0.05
</td>
<td>
0.06
</td>
<td>
70.8%
</td>
<td>
28.0%
</td>
<td>
51.2%
</td>
<td>
44.0%
</td>
<td>
2.4%
</td>
</tr>
<tr>
<td>
Hunter Goodman
</td>
<td>
Colorado Rockies
</td>
<td>
3
</td>
<td>
4.38
</td>
<td>
0.88
</td>
<td>
0.30
</td>
<td>
0.51
</td>
<td>
0.59
</td>
<td>
0.00
</td>
<td>
0.02
</td>
<td>
0.04
</td>
<td>
64.0%
</td>
<td>
28.0%
</td>
<td>
43.2%
</td>
<td>
38.8%
</td>
<td>
0.4%
</td>
</tr>
<tr>
<td>
Jeremy Peña
</td>
<td>
Houston Astros
</td>
<td>
1
</td>
<td>
4.83
</td>
<td>
1.39
</td>
<td>
0.28
</td>
<td>
0.76
</td>
<td>
0.62
</td>
<td>
0.03
</td>
<td>
0.04
</td>
<td>
0.04
</td>
<td>
81.2%
</td>
<td>
25.2%
</td>
<td>
54.0%
</td>
<td>
39.6%
</td>
<td>
2.8%
</td>
</tr>
<tr>
<td>
Ty France
</td>
<td>
San Diego Padres
</td>
<td>
4
</td>
<td>
4.45
</td>
<td>
1.03
</td>
<td>
0.29
</td>
<td>
0.57
</td>
<td>
0.68
</td>
<td>
0.00
</td>
<td>
0.04
</td>
<td>
0.07
</td>
<td>
68.8%
</td>
<td>
25.2%
</td>
<td>
44.8%
</td>
<td>
36.4%
</td>
<td>
0.4%
</td>
</tr>
<tr>
<td>
Ryan O’Hearn
</td>
<td>
Pittsburgh Pirates
</td>
<td>
5
</td>
<td>
4.17
</td>
<td>
0.96
</td>
<td>
0.29
</td>
<td>
0.57
</td>
<td>
0.67
</td>
<td>
0.02
</td>
<td>
0.02
</td>
<td>
0.07
</td>
<td>
63.6%
</td>
<td>
24.8%
</td>
<td>
44.4%
</td>
<td>
36.0%
</td>
<td>
1.6%
</td>
</tr>
<tr>
<td>
Manny Machado
</td>
<td>
San Diego Padres
</td>
<td>
3
</td>
<td>
4.58
</td>
<td>
0.90
</td>
<td>
0.27
</td>
<td>
0.54
</td>
<td>
0.76
</td>
<td>
0.02
</td>
<td>
0.07
</td>
<td>
0.12
</td>
<td>
66.0%
</td>
<td>
24.4%
</td>
<td>
46.0%
</td>
<td>
42.0%
</td>
<td>
2.0%
</td>
</tr>
<tr>
<td>
Pete Crow-Armstrong
</td>
<td>
Chicago Cubs
</td>
<td>
1
</td>
<td>
4.81
</td>
<td>
1.18
</td>
<td>
0.26
</td>
<td>
0.72
</td>
<td>
0.64
</td>
<td>
0.18
</td>
<td>
0.02
</td>
<td>
0.03
</td>
<td>
72.0%
</td>
<td>
24.0%
</td>
<td>
56.4%
</td>
<td>
38.4%
</td>
<td>
16.8%
</td>
</tr>
<tr>
<td>
Dillon Dingler
</td>
<td>
Detroit Tigers
</td>
<td>
5
</td>
<td>
4.28
</td>
<td>
1.06
</td>
<td>
0.27
</td>
<td>
0.64
</td>
<td>
0.90
</td>
<td>
0.00
</td>
<td>
0.08
</td>
<td>
0.09
</td>
<td>
70.8%
</td>
<td>
24.0%
</td>
<td>
46.0%
</td>
<td>
51.6%
</td>
<td>
0.0%
</td>
</tr>
<tr>
<td>
Max Muncy
</td>
<td>
Los Angeles Dodgers
</td>
<td>
4
</td>
<td>
4.60
</td>
<td>
1.05
</td>
<td>
0.27
</td>
<td>
0.68
</td>
<td>
0.83
</td>
<td>
0.01
</td>
<td>
0.06
</td>
<td>
0.08
</td>
<td>
66.0%
</td>
<td>
24.0%
</td>
<td>
50.8%
</td>
<td>
43.6%
</td>
<td>
0.8%
</td>
</tr>
<tr>
<td>
Joc Pederson
</td>
<td>
Texas Rangers
</td>
<td>
1
</td>
<td>
4.43
</td>
<td>
0.86
</td>
<td>
0.25
</td>
<td>
0.54
</td>
<td>
0.46
</td>
<td>
0.02
</td>
<td>
0.01
</td>
<td>
0.03
</td>
<td>
63.6%
</td>
<td>
23.2%
</td>
<td>
43.6%
</td>
<td>
31.2%
</td>
<td>
2.4%
</td>
</tr>
<tr>
<td>
Jacob Gonzalez
</td>
<td>
Pittsburgh Pirates
</td>
<td>
7
</td>
<td>
3.98
</td>
<td>
0.82
</td>
<td>
0.24
</td>
<td>
0.53
</td>
<td>
0.60
</td>
<td>
0.00
</td>
<td>
0.06
</td>
<td>
0.08
</td>
<td>
62.4%
</td>
<td>
23.2%
</td>
<td>
46.4%
</td>
<td>
38.4%
</td>
<td>
0.4%
</td>
</tr>
</tbody>
</table>
</div>
</section>
<div class="method-callout">
<strong>Chronological calibration gate:</strong> The current Phase 4 version starts a separate chronological ledger with its next eligible pregame archive. Prior-version status: awaiting 300 more settled forecasts for plate_appearance_state_machine_phase3_v1 Calibration requires 300 settled forecasts, fits only the earliest 70%, and must improve both win-probability Brier score and team-runs MAE on the later 30% before shadow application.
</div>
<div class="method-callout">
<strong>Current Phase 4 boundary:</strong> park effects are empirical and shrunk, but still descriptive rather than fully adjusted for runner mix, batted-ball direction, and defense. Catcher identity, outfielder conversion skill, errors, pinch hitters, injuries, and transaction-aware bench roles remain the next inputs.
</div>
</section>
<section class="player-probability-room">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Player simulation board · 2,000 draws per lineup</span>
<h2 class="anchored">
Player outcomes now live inside the game simulation
</h2>
<p>
Confirmed orders are simulated through two continuous phases: the probable starter, then the opposing active-roster bullpen. The same draws produce full-game hitter lines and starter strikeout distributions.
</p>
</div>
<div class="player-probability-grid">
<section class="player-prob-board">
<header>
<span class="eyebrow">Starter + bullpen Monte Carlo</span>
<h3 class="anchored">
Home-run probability leaders
</h3>
<p>
Full-game hitter draws include posted batting-order opportunity, the probable starter, the active-roster bullpen quality layer, and the run environment.
</p>
</header>
<div class="table-scroll">
<table class="data-table data-table--compact">
<thead>
<tr>
<th>
Rank
</th>
<th>
Player
</th>
<th>
Team
</th>
<th>
Opponent
</th>
<th>
Probability
</th>
<th>
Mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
1
</td>
<td>
Christian Encarnacion-Strand
</td>
<td>
Baltimore Orioles
</td>
<td>
Atlanta Braves
</td>
<td>
40.5%
</td>
<td>
0.48
</td>
</tr>
<tr>
<td>
2
</td>
<td>
Esmerlyn Valdez
</td>
<td>
Pittsburgh Pirates
</td>
<td>
Chicago Cubs
</td>
<td>
36.1%
</td>
<td>
0.44
</td>
</tr>
<tr>
<td>
3
</td>
<td>
Byron Buxton
</td>
<td>
Minnesota Twins
</td>
<td>
Athletics
</td>
<td>
30.9%
</td>
<td>
0.36
</td>
</tr>
<tr>
<td>
4
</td>
<td>
Yordan Alvarez
</td>
<td>
Houston Astros
</td>
<td>
Chicago White Sox
</td>
<td>
30.9%
</td>
<td>
0.36
</td>
</tr>
<tr>
<td>
5
</td>
<td>
Luke Maile
</td>
<td>
Kansas City Royals
</td>
<td>
Detroit Tigers
</td>
<td>
29.1%
</td>
<td>
0.33
</td>
</tr>
<tr>
<td>
6
</td>
<td>
Munetaka Murakami
</td>
<td>
Chicago White Sox
</td>
<td>
Houston Astros
</td>
<td>
28.7%
</td>
<td>
0.33
</td>
</tr>
<tr>
<td>
7
</td>
<td>
Hunter Goodman
</td>
<td>
Colorado Rockies
</td>
<td>
Milwaukee Brewers
</td>
<td>
24.2%
</td>
<td>
0.27
</td>
</tr>
<tr>
<td>
8
</td>
<td>
Ty France
</td>
<td>
San Diego Padres
</td>
<td>
Miami Marlins
</td>
<td>
24.1%
</td>
<td>
0.27
</td>
</tr>
<tr>
<td>
9
</td>
<td>
Manny Machado
</td>
<td>
San Diego Padres
</td>
<td>
Miami Marlins
</td>
<td>
23.4%
</td>
<td>
0.26
</td>
</tr>
<tr>
<td>
10
</td>
<td>
Jordan Walker
</td>
<td>
St.&nbsp;Louis Cardinals
</td>
<td>
Cincinnati Reds
</td>
<td>
22.9%
</td>
<td>
0.26
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="player-prob-board">
<header>
<span class="eyebrow">Starter + bullpen Monte Carlo</span>
<h3 class="anchored">
Hit probability leaders
</h3>
<p>
Each hitter continues through the same batting order when the simulation moves from the starter phase to the bullpen.
</p>
</header>
<div class="table-scroll">
<table class="data-table data-table--compact">
<thead>
<tr>
<th>
Rank
</th>
<th>
Player
</th>
<th>
Team
</th>
<th>
Opponent
</th>
<th>
Probability
</th>
<th>
Mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
1
</td>
<td>
Jake Mangum
</td>
<td>
Pittsburgh Pirates
</td>
<td>
Chicago Cubs
</td>
<td>
81.6%
</td>
<td>
1.42
</td>
</tr>
<tr>
<td>
2
</td>
<td>
Otto Lopez
</td>
<td>
Miami Marlins
</td>
<td>
San Diego Padres
</td>
<td>
80.8%
</td>
<td>
1.36
</td>
</tr>
<tr>
<td>
3
</td>
<td>
Jackson Chourio
</td>
<td>
Milwaukee Brewers
</td>
<td>
Colorado Rockies
</td>
<td>
79.5%
</td>
<td>
1.31
</td>
</tr>
<tr>
<td>
4
</td>
<td>
Jeremy Peña
</td>
<td>
Houston Astros
</td>
<td>
Chicago White Sox
</td>
<td>
77.8%
</td>
<td>
1.29
</td>
</tr>
<tr>
<td>
5
</td>
<td>
Nick Gonzales
</td>
<td>
Pittsburgh Pirates
</td>
<td>
Chicago Cubs
</td>
<td>
77.6%
</td>
<td>
1.25
</td>
</tr>
<tr>
<td>
6
</td>
<td>
Gabriel Moreno
</td>
<td>
Arizona Diamondbacks
</td>
<td>
Washington Nationals
</td>
<td>
77.5%
</td>
<td>
1.27
</td>
</tr>
<tr>
<td>
7
</td>
<td>
Byron Buxton
</td>
<td>
Minnesota Twins
</td>
<td>
Athletics
</td>
<td>
77.5%
</td>
<td>
1.24
</td>
</tr>
<tr>
<td>
8
</td>
<td>
Sam Antonacci
</td>
<td>
Chicago White Sox
</td>
<td>
Houston Astros
</td>
<td>
77.4%
</td>
<td>
1.29
</td>
</tr>
<tr>
<td>
9
</td>
<td>
Luis Arraez
</td>
<td>
San Francisco Giants
</td>
<td>
Los Angeles Angels
</td>
<td>
77.2%
</td>
<td>
1.24
</td>
</tr>
<tr>
<td>
10
</td>
<td>
Andrew Vaughn
</td>
<td>
Milwaukee Brewers
</td>
<td>
Colorado Rockies
</td>
<td>
77.0%
</td>
<td>
1.24
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="player-prob-board">
<header>
<span class="eyebrow">Starter + bullpen Monte Carlo</span>
<h3 class="anchored">
Extra-base-hit probability leaders
</h3>
<p>
Doubles, triples, and home runs are simulated as mutually exclusive plate-appearance outcomes.
</p>
</header>
<div class="table-scroll">
<table class="data-table data-table--compact">
<thead>
<tr>
<th>
Rank
</th>
<th>
Player
</th>
<th>
Team
</th>
<th>
Opponent
</th>
<th>
Probability
</th>
<th>
Mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
1
</td>
<td>
Corbin Carroll
</td>
<td>
Arizona Diamondbacks
</td>
<td>
Washington Nationals
</td>
<td>
48.0%
</td>
<td>
0.61
</td>
</tr>
<tr>
<td>
2
</td>
<td>
Andrew Vaughn
</td>
<td>
Milwaukee Brewers
</td>
<td>
Colorado Rockies
</td>
<td>
45.1%
</td>
<td>
0.56
</td>
</tr>
<tr>
<td>
3
</td>
<td>
Shawn Ross
</td>
<td>
Pittsburgh Pirates
</td>
<td>
Chicago Cubs
</td>
<td>
45.0%
</td>
<td>
0.56
</td>
</tr>
<tr>
<td>
4
</td>
<td>
Byron Buxton
</td>
<td>
Minnesota Twins
</td>
<td>
Athletics
</td>
<td>
42.0%
</td>
<td>
0.52
</td>
</tr>
<tr>
<td>
5
</td>
<td>
Tommy White
</td>
<td>
Athletics
</td>
<td>
Minnesota Twins
</td>
<td>
41.9%
</td>
<td>
0.50
</td>
</tr>
<tr>
<td>
6
</td>
<td>
Kody Clemens
</td>
<td>
Minnesota Twins
</td>
<td>
Athletics
</td>
<td>
41.9%
</td>
<td>
0.49
</td>
</tr>
<tr>
<td>
7
</td>
<td>
Brice Turang
</td>
<td>
Milwaukee Brewers
</td>
<td>
Colorado Rockies
</td>
<td>
40.6%
</td>
<td>
0.49
</td>
</tr>
<tr>
<td>
8
</td>
<td>
Otto Lopez
</td>
<td>
Miami Marlins
</td>
<td>
San Diego Padres
</td>
<td>
40.6%
</td>
<td>
0.51
</td>
</tr>
<tr>
<td>
9
</td>
<td>
Christian Encarnacion-Strand
</td>
<td>
Baltimore Orioles
</td>
<td>
Atlanta Braves
</td>
<td>
40.5%
</td>
<td>
0.48
</td>
</tr>
<tr>
<td>
10
</td>
<td>
Tristan Peters
</td>
<td>
Chicago White Sox
</td>
<td>
Houston Astros
</td>
<td>
40.4%
</td>
<td>
0.48
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="player-prob-board">
<header>
<span class="eyebrow">Starter + bullpen Monte Carlo</span>
<h3 class="anchored">
Two-plus total-base leaders
</h3>
<p>
The total-base board preserves each simulated event mix instead of treating every hit as equivalent.
</p>
</header>
<div class="table-scroll">
<table class="data-table data-table--compact">
<thead>
<tr>
<th>
Rank
</th>
<th>
Player
</th>
<th>
Team
</th>
<th>
Opponent
</th>
<th>
Probability
</th>
<th>
Mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
1
</td>
<td>
Otto Lopez
</td>
<td>
Miami Marlins
</td>
<td>
San Diego Padres
</td>
<td>
55.4%
</td>
<td>
2.09
</td>
</tr>
<tr>
<td>
2
</td>
<td>
Andrew Vaughn
</td>
<td>
Milwaukee Brewers
</td>
<td>
Colorado Rockies
</td>
<td>
55.0%
</td>
<td>
2.01
</td>
</tr>
<tr>
<td>
3
</td>
<td>
Jake Mangum
</td>
<td>
Pittsburgh Pirates
</td>
<td>
Chicago Cubs
</td>
<td>
54.9%
</td>
<td>
1.88
</td>
</tr>
<tr>
<td>
4
</td>
<td>
Corbin Carroll
</td>
<td>
Arizona Diamondbacks
</td>
<td>
Washington Nationals
</td>
<td>
53.9%
</td>
<td>
2.13
</td>
</tr>
<tr>
<td>
5
</td>
<td>
Jackson Chourio
</td>
<td>
Milwaukee Brewers
</td>
<td>
Colorado Rockies
</td>
<td>
53.0%
</td>
<td>
2.24
</td>
</tr>
<tr>
<td>
6
</td>
<td>
Byron Buxton
</td>
<td>
Minnesota Twins
</td>
<td>
Athletics
</td>
<td>
53.0%
</td>
<td>
2.49
</td>
</tr>
<tr>
<td>
7
</td>
<td>
Yordan Alvarez
</td>
<td>
Houston Astros
</td>
<td>
Chicago White Sox
</td>
<td>
50.6%
</td>
<td>
2.41
</td>
</tr>
<tr>
<td>
8
</td>
<td>
Jordan Walker
</td>
<td>
St.&nbsp;Louis Cardinals
</td>
<td>
Cincinnati Reds
</td>
<td>
50.4%
</td>
<td>
2.16
</td>
</tr>
<tr>
<td>
9
</td>
<td>
Sam Antonacci
</td>
<td>
Chicago White Sox
</td>
<td>
Houston Astros
</td>
<td>
50.3%
</td>
<td>
1.92
</td>
</tr>
<tr>
<td>
10
</td>
<td>
Brice Turang
</td>
<td>
Milwaukee Brewers
</td>
<td>
Colorado Rockies
</td>
<td>
49.9%
</td>
<td>
2.01
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="player-prob-board">
<header>
<span class="eyebrow">Starter + bullpen Monte Carlo</span>
<h3 class="anchored">
Five-plus strikeout leaders
</h3>
<p>
Probable starters draw a game-specific batters-faced distribution against the posted opposing order.
</p>
</header>
<div class="table-scroll">
<table class="data-table data-table--compact">
<thead>
<tr>
<th>
Rank
</th>
<th>
Player
</th>
<th>
Team
</th>
<th>
Opponent
</th>
<th>
Probability
</th>
<th>
Mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
1
</td>
<td>
Jacob Misiorowski
</td>
<td>
Milwaukee Brewers
</td>
<td>
Colorado Rockies
</td>
<td>
80.9%
</td>
<td>
6.49
</td>
</tr>
<tr>
<td>
2
</td>
<td>
Reynaldo López
</td>
<td>
Atlanta Braves
</td>
<td>
Baltimore Orioles
</td>
<td>
79.0%
</td>
<td>
6.38
</td>
</tr>
<tr>
<td>
3
</td>
<td>
Luinder Avila
</td>
<td>
Kansas City Royals
</td>
<td>
Detroit Tigers
</td>
<td>
73.4%
</td>
<td>
6.00
</td>
</tr>
<tr>
<td>
4
</td>
<td>
Braxton Ashcraft
</td>
<td>
Pittsburgh Pirates
</td>
<td>
Chicago Cubs
</td>
<td>
73.0%
</td>
<td>
5.96
</td>
</tr>
<tr>
<td>
5
</td>
<td>
Jacob deGrom
</td>
<td>
Texas Rangers
</td>
<td>
Seattle Mariners
</td>
<td>
73.0%
</td>
<td>
5.85
</td>
</tr>
<tr>
<td>
6
</td>
<td>
Logan Gilbert
</td>
<td>
Seattle Mariners
</td>
<td>
Texas Rangers
</td>
<td>
70.0%
</td>
<td>
5.81
</td>
</tr>
<tr>
<td>
7
</td>
<td>
Kevin Gausman
</td>
<td>
Toronto Blue Jays
</td>
<td>
Boston Red Sox
</td>
<td>
65.0%
</td>
<td>
5.34
</td>
</tr>
<tr>
<td>
8
</td>
<td>
José Soriano
</td>
<td>
Los Angeles Angels
</td>
<td>
San Francisco Giants
</td>
<td>
64.7%
</td>
<td>
5.36
</td>
</tr>
<tr>
<td>
9
</td>
<td>
Ronel Blanco
</td>
<td>
Houston Astros
</td>
<td>
Chicago White Sox
</td>
<td>
62.5%
</td>
<td>
5.27
</td>
</tr>
<tr>
<td>
10
</td>
<td>
Jameson Taillon
</td>
<td>
Chicago Cubs
</td>
<td>
Pittsburgh Pirates
</td>
<td>
59.9%
</td>
<td>
5.12
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="player-prob-board">
<header>
<span class="eyebrow">Starter + bullpen Monte Carlo</span>
<h3 class="anchored">
Seven-plus strikeout leaders
</h3>
<p>
The upper-tail board responds to starter workload, the opposing order, and both pitcher and hitter strikeout rates.
</p>
</header>
<div class="table-scroll">
<table class="data-table data-table--compact">
<thead>
<tr>
<th>
Rank
</th>
<th>
Player
</th>
<th>
Team
</th>
<th>
Opponent
</th>
<th>
Probability
</th>
<th>
Mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
1
</td>
<td>
Jacob Misiorowski
</td>
<td>
Milwaukee Brewers
</td>
<td>
Colorado Rockies
</td>
<td>
48.9%
</td>
<td>
6.49
</td>
</tr>
<tr>
<td>
2
</td>
<td>
Reynaldo López
</td>
<td>
Atlanta Braves
</td>
<td>
Baltimore Orioles
</td>
<td>
46.8%
</td>
<td>
6.38
</td>
</tr>
<tr>
<td>
3
</td>
<td>
Luinder Avila
</td>
<td>
Kansas City Royals
</td>
<td>
Detroit Tigers
</td>
<td>
40.6%
</td>
<td>
6.00
</td>
</tr>
<tr>
<td>
4
</td>
<td>
Braxton Ashcraft
</td>
<td>
Pittsburgh Pirates
</td>
<td>
Chicago Cubs
</td>
<td>
39.1%
</td>
<td>
5.96
</td>
</tr>
<tr>
<td>
5
</td>
<td>
Logan Gilbert
</td>
<td>
Seattle Mariners
</td>
<td>
Texas Rangers
</td>
<td>
37.1%
</td>
<td>
5.81
</td>
</tr>
<tr>
<td>
6
</td>
<td>
Jacob deGrom
</td>
<td>
Texas Rangers
</td>
<td>
Seattle Mariners
</td>
<td>
36.1%
</td>
<td>
5.85
</td>
</tr>
<tr>
<td>
7
</td>
<td>
José Soriano
</td>
<td>
Los Angeles Angels
</td>
<td>
San Francisco Giants
</td>
<td>
28.0%
</td>
<td>
5.36
</td>
</tr>
<tr>
<td>
8
</td>
<td>
Kevin Gausman
</td>
<td>
Toronto Blue Jays
</td>
<td>
Boston Red Sox
</td>
<td>
27.5%
</td>
<td>
5.34
</td>
</tr>
<tr>
<td>
9
</td>
<td>
Ronel Blanco
</td>
<td>
Houston Astros
</td>
<td>
Chicago White Sox
</td>
<td>
27.4%
</td>
<td>
5.27
</td>
</tr>
<tr>
<td>
10
</td>
<td>
Erick Fedde
</td>
<td>
Chicago White Sox
</td>
<td>
Houston Astros
</td>
<td>
23.9%
</td>
<td>
5.09
</td>
</tr>
</tbody>
</table>
</div>
</section>
</div>
<div class="method-callout">
<strong>Development boundary:</strong> this established player board remains the comparison model. The Phase 4 section above now adds named relievers, player-specific running tendencies, pitcher hold, productive outs, steals, and empirical park advancement; neither board will be promoted until clean pregame grading identifies which construction is better calibrated.
</div>
</section>
<section class="section-heading">
<span class="eyebrow">Development projection board</span>
<h2 class="anchored">
The actual slate in one scan
</h2>
<p>
Each game card now comes from today’s schedule and shows the simulated win split, score center, uncertainty, close-game chance, and input status. These are pre-calibration research outputs, not public betting forecasts.
</p>
</section>
<div class="projection-slate-grid">
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 1 · scheduled slate</span><span class="projection-lean">Narrow lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Cleveland Guardians</strong></span><b>44.7%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Tampa Bay Rays</strong></span><b>55.3%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Cleveland Guardians 44.7% Tampa Bay Rays 55.3%">
<span class="is-away" style="width:44.7%"></span><span class="is-home" style="width:55.3%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>3.6 – 3.9</strong></span><span><small>Model total</small><strong>7.5</strong></span><span><small>One-run game</small><strong>38.9%</strong></span>
</div>
<footer>
<strong>Tampa Bay Rays 55.3%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 2 · scheduled slate</span><span class="projection-lean">Clear lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Arizona Diamondbacks</strong></span><b>66.1%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Washington Nationals</strong></span><b>33.9%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Arizona Diamondbacks 66.1% Washington Nationals 33.9%">
<span class="is-away" style="width:66.1%"></span><span class="is-home" style="width:33.9%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>5.3 – 4.1</strong></span><span><small>Model total</small><strong>9.4</strong></span><span><small>One-run game</small><strong>32.6%</strong></span>
</div>
<footer>
<strong>Arizona Diamondbacks 66.1%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 3 · scheduled slate</span><span class="projection-lean">Clear lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Chicago Cubs</strong></span><b>29.1%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Pittsburgh Pirates</strong></span><b>70.9%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Chicago Cubs 29.1% Pittsburgh Pirates 70.9%">
<span class="is-away" style="width:29.1%"></span><span class="is-home" style="width:70.9%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>4.5 – 6.4</strong></span><span><small>Model total</small><strong>10.9</strong></span><span><small>One-run game</small><strong>28.1%</strong></span>
</div>
<footer>
<strong>Pittsburgh Pirates 70.9%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 4 · scheduled slate</span><span class="projection-lean">Narrow lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Toronto Blue Jays</strong></span><b>40.6%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Boston Red Sox</strong></span><b>59.4%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Toronto Blue Jays 40.6% Boston Red Sox 59.4%">
<span class="is-away" style="width:40.6%"></span><span class="is-home" style="width:59.4%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>3.2 – 3.8</strong></span><span><small>Model total</small><strong>7.0</strong></span><span><small>One-run game</small><strong>40.2%</strong></span>
</div>
<footer>
<strong>Boston Red Sox 59.4%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 5 · scheduled slate</span><span class="projection-lean">Clear lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Atlanta Braves</strong></span><b>38.1%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Baltimore Orioles</strong></span><b>61.9%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Atlanta Braves 38.1% Baltimore Orioles 61.9%">
<span class="is-away" style="width:38.1%"></span><span class="is-home" style="width:61.9%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>4.3 – 5.3</strong></span><span><small>Model total</small><strong>9.6</strong></span><span><small>One-run game</small><strong>33.7%</strong></span>
</div>
<footer>
<strong>Baltimore Orioles 61.9%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 6 · scheduled slate</span><span class="projection-lean">Clear lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Kansas City Royals</strong></span><b>35.0%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Detroit Tigers</strong></span><b>65.0%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Kansas City Royals 35.0% Detroit Tigers 65.0%">
<span class="is-away" style="width:35%"></span><span class="is-home" style="width:65%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>4.3 – 5.5</strong></span><span><small>Model total</small><strong>9.8</strong></span><span><small>One-run game</small><strong>32.3%</strong></span>
</div>
<footer>
<strong>Detroit Tigers 65.0%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 7 · scheduled slate</span><span class="projection-lean">Clear lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Los Angeles Dodgers</strong></span><b>70.4%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>New York Mets</strong></span><b>29.6%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Los Angeles Dodgers 70.4% New York Mets 29.6%">
<span class="is-away" style="width:70.4%"></span><span class="is-home" style="width:29.6%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>5.3 – 3.7</strong></span><span><small>Model total</small><strong>9.0</strong></span><span><small>One-run game</small><strong>31.5%</strong></span>
</div>
<footer>
<strong>Los Angeles Dodgers 70.4%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 8 · scheduled slate</span><span class="projection-lean">Near toss-up</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>San Diego Padres</strong></span><b>52.5%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Miami Marlins</strong></span><b>47.5%</b>
</div>
<div class="projection-win-track" role="img" aria-label="San Diego Padres 52.5% Miami Marlins 47.5%">
<span class="is-away" style="width:52.5%"></span><span class="is-home" style="width:47.5%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>5.0 – 4.8</strong></span><span><small>Model total</small><strong>9.8</strong></span><span><small>One-run game</small><strong>34.4%</strong></span>
</div>
<footer>
<strong>San Diego Padres 52.5%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 9 · scheduled slate</span><span class="projection-lean">Clear lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Athletics</strong></span><b>30.1%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Minnesota Twins</strong></span><b>69.9%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Athletics 30.1% Minnesota Twins 69.9%">
<span class="is-away" style="width:30.1%"></span><span class="is-home" style="width:69.9%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>4.4 – 6.1</strong></span><span><small>Model total</small><strong>10.5</strong></span><span><small>One-run game</small><strong>29.1%</strong></span>
</div>
<footer>
<strong>Minnesota Twins 69.9%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 10 · scheduled slate</span><span class="projection-lean">Narrow lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Houston Astros</strong></span><b>42.2%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Chicago White Sox</strong></span><b>57.8%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Houston Astros 42.2% Chicago White Sox 57.8%">
<span class="is-away" style="width:42.2%"></span><span class="is-home" style="width:57.8%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>5.3 – 6.0</strong></span><span><small>Model total</small><strong>11.2</strong></span><span><small>One-run game</small><strong>31.8%</strong></span>
</div>
<footer>
<strong>Chicago White Sox 57.8%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 11 · scheduled slate</span><span class="projection-lean">Clear lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Colorado Rockies</strong></span><b>16.4%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Milwaukee Brewers</strong></span><b>83.6%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Colorado Rockies 16.4% Milwaukee Brewers 83.6%">
<span class="is-away" style="width:16.4%"></span><span class="is-home" style="width:83.6%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>3.1 – 6.1</strong></span><span><small>Model total</small><strong>9.2</strong></span><span><small>One-run game</small><strong>23.2%</strong></span>
</div>
<footer>
<strong>Milwaukee Brewers 83.6%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 12 · scheduled slate</span><span class="projection-lean">Clear lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Cincinnati Reds</strong></span><b>38.8%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>St.&nbsp;Louis Cardinals</strong></span><b>61.2%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Cincinnati Reds 38.8% St. Louis Cardinals 61.2%">
<span class="is-away" style="width:38.8%"></span><span class="is-home" style="width:61.2%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>4.1 – 4.9</strong></span><span><small>Model total</small><strong>9.0</strong></span><span><small>One-run game</small><strong>34.7%</strong></span>
</div>
<footer>
<strong>St.&nbsp;Louis Cardinals 61.2%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 13 · scheduled slate</span><span class="projection-lean">Near toss-up</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Seattle Mariners</strong></span><b>46.9%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Texas Rangers</strong></span><b>53.1%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Seattle Mariners 46.9% Texas Rangers 53.1%">
<span class="is-away" style="width:46.9%"></span><span class="is-home" style="width:53.1%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>4.0 – 4.3</strong></span><span><small>Model total</small><strong>8.3</strong></span><span><small>One-run game</small><strong>37.7%</strong></span>
</div>
<footer>
<strong>Texas Rangers 53.1%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 14 · scheduled slate</span><span class="projection-lean">Narrow lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>Los Angeles Angels</strong></span><b>55.2%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>San Francisco Giants</strong></span><b>44.8%</b>
</div>
<div class="projection-win-track" role="img" aria-label="Los Angeles Angels 55.2% San Francisco Giants 44.8%">
<span class="is-away" style="width:55.2%"></span><span class="is-home" style="width:44.8%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>4.7 – 4.3</strong></span><span><small>Model total</small><strong>8.9</strong></span><span><small>One-run game</small><strong>35.5%</strong></span>
</div>
<footer>
<strong>Los Angeles Angels 55.2%</strong><span>20,000 draws · confirmed orders · matched starters</span>
</footer>
</article>
<article class="projection-game-card">
<header>
<span class="eyebrow">Game 15 · scheduled slate</span><span class="projection-lean">Narrow lean</span>
</header>
<div class="projection-team-row">
<span><small>Away</small><strong>New York Yankees</strong></span><b>42.2%</b>
</div>
<div class="projection-team-row">
<span><small>Home</small><strong>Philadelphia Phillies</strong></span><b>57.8%</b>
</div>
<div class="projection-win-track" role="img" aria-label="New York Yankees 42.2% Philadelphia Phillies 57.8%">
<span class="is-away" style="width:42.2%"></span><span class="is-home" style="width:57.8%"></span>
</div>
<div class="projection-score-strip">
<span><small>Mean score</small><strong>3.3 – 3.8</strong></span><span><small>Model total</small><strong>7.0</strong></span><span><small>One-run game</small><strong>39.7%</strong></span>
</div>
<footer>
<strong>Philadelphia Phillies 57.8%</strong><span>20,000 draws · conditional orders · matched starters</span>
</footer>
</article>
</div>
<section class="projection-feature">
<div class="projection-feature__head">
<div>
<span class="eyebrow">Feature simulation · 20,000 draws</span>
<h2 class="anchored">
San Diego Padres at Miami Marlins
</h2>
<p>
The closest matchup on today’s scheduled slate shows the current score distribution, model drivers, and honest input limitations.
</p>
</div>
<div class="projection-feature__call">
<small>Model lean</small><strong>San Diego Padres</strong><span>52.5%</span>
</div>
</div>
<div class="projection-matchup-score">
<div>
<span>San Diego Padres</span><strong>5.0</strong><small>80% range 2–8</small>
</div>
<i aria-hidden="true">at</i>
<div>
<span>Miami Marlins</span><strong>4.8</strong><small>80% range 2–8</small>
</div>
</div>
<div class="projection-feature__grid">
<section>
<div class="context-subhead">
<span>Winning-margin distribution</span><small>Away ← outcome → Home</small>
</div>
<div class="margin-distribution">
<div class="margin-row">
<span>Away by 5+</span>
<div class="margin-row__track">
<i style="width:44.2%"></i>
</div>
<strong>7.8%</strong>
</div>
<div class="margin-row">
<span>Away by 3-4</span>
<div class="margin-row__track">
<i style="width:82.8%"></i>
</div>
<strong>14.7%</strong>
</div>
<div class="margin-row">
<span>Away by 2</span>
<div class="margin-row__track">
<i style="width:68.2%"></i>
</div>
<strong>12.1%</strong>
</div>
<div class="margin-row">
<span>Away by 1</span>
<div class="margin-row__track">
<i style="width:100.0%"></i>
</div>
<strong>17.8%</strong>
</div>
<div class="margin-row">
<span>Home by 1</span>
<div class="margin-row__track">
<i style="width:93.7%"></i>
</div>
<strong>16.7%</strong>
</div>
<div class="margin-row">
<span>Home by 2</span>
<div class="margin-row__track">
<i style="width:62.3%"></i>
</div>
<strong>11.1%</strong>
</div>
<div class="margin-row">
<span>Home by 3-4</span>
<div class="margin-row__track">
<i style="width:73.6%"></i>
</div>
<strong>13.1%</strong>
</div>
<div class="margin-row">
<span>Home by 5+</span>
<div class="margin-row__track">
<i style="width:37.8%"></i>
</div>
<strong>6.7%</strong>
</div>
</div>
</section>
<section>
<div class="context-subhead">
<span>Why the model lands here</span><small>League ranks</small>
</div>
<ol class="projection-driver-list">
<li>
<span>Posted-lineup offense</span><strong>Miami Marlins</strong><small>103 vs 109 blended wRC+ after platoon and recent-form adjustments</small>
</li>
<li>
<span>Probable starter</span><strong>San Diego Padres</strong><small>Walker Buehler 4.5 vs Janson Junk 4.65 form-adjusted run estimator</small>
</li>
<li>
<span>Available bullpen</span><strong>San Diego Padres</strong><small>3.38 vs 4.17 FIP blend with active reliever selector</small>
</li>
<li>
<span>Park and weather</span><strong>Run environment</strong><small>80 F temperature adjustment; park factor 1</small>
</li>
</ol>
</section>
</div>
<div class="projection-outcome-grid">
<span><small>Mean total</small><strong>9.8</strong><em>80% range 6–14</em></span><span><small>One-run game</small><strong>34.4%</strong><em>Close-game likelihood</em></span><span><small>Extras</small><strong>12.9%</strong><em>Regulation tie rate</em></span><span><small>Bullpen effect</small><strong>-6.7 pts</strong><em>Home win probability subtracts</em></span>
</div>
<div class="projection-scorelines">
<div class="context-subhead">
<span>Most common exact scores</span><small>Away – home</small>
</div>
<div>
<span><small>#1 exact score</small><strong>5 – 4</strong><em>4.6%</em></span><span><small>#2 exact score</small><strong>4 – 5</strong><em>4.0%</em></span><span><small>#3 exact score</small><strong>6 – 5</strong><em>3.7%</em></span><span><small>#4 exact score</small><strong>4 – 3</strong><em>3.4%</em></span><span><small>#5 exact score</small><strong>5 – 6</strong><em>3.4%</em></span>
</div>
</div>
</section>
<section class="projection-readiness">
<div class="projection-readiness__head">
<div>
<span class="eyebrow">Publication gate · July 26, 2026</span>
<h2 class="anchored">
The scheduled-game engine is running behind a calibration wall
</h2>
<p>
The page can now simulate today’s actual games. Development probabilities stay clearly labeled until current PBP workload, empirical park effects, and a chronological backtest pass.
</p>
</div>
<div class="projection-readiness__score">
<strong>57.1%</strong><span>activation gates closed</span>
</div>
</div>
<div class="projection-input-grid">
<article class="projection-input-gate is-ready">
<span>Ready</span>
<h3 class="anchored">
Scheduled games
</h3>
<p>
15 games
</p>
</article>
<article class="projection-input-gate is-missing">
<span>Open gate</span>
<h3 class="anchored">
Posted lineups
</h3>
<p>
14/15 confirmed
</p>
</article>
<article class="projection-input-gate is-ready">
<span>Ready</span>
<h3 class="anchored">
Probable starters
</h3>
<p>
15/15 matched
</p>
</article>
<article class="projection-input-gate is-ready">
<span>Ready</span>
<h3 class="anchored">
Active bullpens
</h3>
<p>
Roster verified
</p>
</article>
<article class="projection-input-gate is-ready">
<span>Ready</span>
<h3 class="anchored">
Current PBP usage
</h3>
<p>
Current
</p>
</article>
<article class="projection-input-gate is-missing">
<span>Open gate</span>
<h3 class="anchored">
Park factors
</h3>
<p>
Neutral placeholder
</p>
</article>
<article class="projection-input-gate is-missing">
<span>Open gate</span>
<h3 class="anchored">
Chronological calibration
</h3>
<p>
Not yet passed
</p>
</article>
</div>
</section>
<section class="projection-feedback-room">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Model fitting · no-lookahead evaluation</span>
<h2 class="anchored">
Real outcomes change the model only after they earn the right
</h2>
<p>
The fitted score layer learned from prior-only rolling team production, then faced a completely later block of games. It improved the raw score scale and narrowly beat the simple home-team Brier baseline, earning shadow-mode evaluation without overwriting the public board.
</p>
</div>
<div class="projection-diagnostic-layout">
<figure class="figure">
<img src="images/graphics-feed/projection-calibration-curve.png?v=20260726145701" alt="Calibration curve comparing historical predicted home-win probability with observed home-win rate" class="figure-img">
<figcaption>
Points show non-empty probability bins; labels are holdout game counts. The dashed line is perfect calibration.
</figcaption>
</figure>
<div class="projection-diagnostic-stats">
<article class="data-card data-card--navy">
<span class="eyebrow">Holdout</span>
<h3 class="anchored">
Later games only
</h3>
<div class="data-card__value">
282
</div>
<p>
Training ended June 26
</p>
</article>
<article class="data-card data-card--red">
<span class="eyebrow">Win probability</span>
<h3 class="anchored">
Brier score
</h3>
<div class="data-card__value">
0.249
</div>
<p>
Naive home baseline 0.251 - Shadow-mode eligible
</p>
</article>
<article class="data-card data-card--steel">
<span class="eyebrow">Run expectation</span>
<h3 class="anchored">
Team-runs MAE
</h3>
<div class="data-card__value">
2.63
</div>
<p>
Raw scale 2.93 before fitting
</p>
</article>
<article class="data-card data-card--navy">
<span class="eyebrow">Live feedback</span>
<h3 class="anchored">
Eligible forecasts
</h3>
<div class="data-card__value">
36
</div>
<p>
264 more game forecasts before live probability calibration
</p>
</article>
</div>
</div>
<div class="projection-feedback-steps">
<article>
<span>01</span>
<h3 class="anchored">
Freeze before first pitch
</h3>
<p>
Every game and player-event probability is archived with its inputs and model version. Late builds are permanently excluded.
</p>
</article>
<article>
<span>02</span>
<h3 class="anchored">
Settle against final PBP
</h3>
<p>
Team scores, winners, hitter events, and starter strikeouts are joined by exact game and MLBAM player IDs.
</p>
</article>
<article>
<span>03</span>
<h3 class="anchored">
Diagnose the misses
</h3>
<p>
Brier score, log loss, run MAE, calibration bins, and player-event residuals reveal whether the model is too aggressive or too conservative.
</p>
</article>
<article>
<span>04</span>
<h3 class="anchored">
Refit in chronological blocks
</h3>
<p>
Only coefficients that improve later unseen games enter shadow mode; public probabilities require a second approval gate.
</p>
</article>
</div>
<div class="method-callout">
<strong>Why today does not count:</strong> the first ledger snapshot was taken after first pitch, so all 15 games were correctly marked late and excluded. The automated daily job will archive future boards before games begin.
</div>
</section>
<section class="hook-path-section">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Starter decision path</span>
<h2 class="anchored">
The handoff becomes part of every game simulation
</h2>
<p>
A fixed tied-game workload path shows when the pooled hook model begins shifting probability toward the bullpen.
</p>
</div>
<div class="hook-path">
<article class="hook-path-node">
<header>
<span>Inning 5</span><strong>4.0%</strong>
</header>
<h3 class="anchored">
Hold the starter
</h3>
<p>
72 pitches · 19 BF · 2x through
</p>
<div class="hook-path-track" role="img" aria-label="Hook probability 4.0%">
<i style="width:4.0%"></i>
</div>
</article>
<article class="hook-path-node">
<header>
<span>Inning 6</span><strong>32.0%</strong>
</header>
<h3 class="anchored">
First major decision
</h3>
<p>
88 pitches · 24 BF · 3x through
</p>
<div class="hook-path-track" role="img" aria-label="Hook probability 32.0%">
<i style="width:32.0%"></i>
</div>
</article>
<article class="hook-path-node">
<header>
<span>Inning 7</span><strong>83.9%</strong>
</header>
<h3 class="anchored">
Bullpen strongly enters
</h3>
<p>
105 pitches · 28 BF · 3x through
</p>
<div class="hook-path-track" role="img" aria-label="Hook probability 83.9%">
<i style="width:83.9%"></i>
</div>
</article>
</div>
<p class="method-note">
Descriptive pooled-model scenarios, not causal manager tendencies or a forecast for a named starter.
</p>
</section>
<section class="bullpen-chain-section">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Reliever chain planner</span>
<h2 class="anchored">
Handedness, leverage, and fatigue change the next arm
</h2>
<p>
Once a starter exits, each three-batter pocket reranks the available bullpen and carries planned workload into the next decision.
</p>
</div>
<div class="bullpen-chain-grid">
<article class="bullpen-chain">
<header>
<div>
<span class="eyebrow">Defending Milwaukee Brewers</span>
<h3 class="anchored">
New York Yankees bullpen path
</h3>
</div>
<span>Scenario</span>
</header>
<ol>
<li>
<div class="bullpen-chain-step__inning">
<span>7</span><small>inning</small>
</div>
<div class="bullpen-chain-step__body">
<header>
<span>Bridge pocket · vs LHB</span><strong>91.8</strong>
</header>
<h3 class="anchored">
Ryan Yarbrough <small>LHP</small>
</h3>
<p>
Availability 100.0% · matchup 100.0% · planned 12 pitches
</p>
<footer>
Alternatives: Paul Blackburn
</footer>
</div>
</li>
<li>
<div class="bullpen-chain-step__inning">
<span>8</span><small>inning</small>
</div>
<div class="bullpen-chain-step__body">
<header>
<span>Setup pocket · vs RHB</span><strong>80.4</strong>
</header>
<h3 class="anchored">
Paul Blackburn <small>RHP</small>
</h3>
<p>
Availability 100.0% · matchup 70.0% · planned 12 pitches
</p>
<footer>
Alternatives: Ryan Yarbrough
</footer>
</div>
</li>
<li>
<div class="bullpen-chain-step__inning">
<span>9</span><small>inning</small>
</div>
<div class="bullpen-chain-step__body">
<header>
<span>Finish pocket · vs RHB</span><strong>68.2</strong>
</header>
<h3 class="anchored">
Paul Blackburn <small>RHP</small>
</h3>
<p>
Availability 72.5% · matchup 70.0% · planned 12 pitches
</p>
<footer>
Alternatives: Ryan Yarbrough
</footer>
</div>
</li>
</ol>
</article>
<article class="bullpen-chain">
<header>
<div>
<span class="eyebrow">Defending New York Yankees</span>
<h3 class="anchored">
Milwaukee Brewers bullpen path
</h3>
</div>
<span>Scenario</span>
</header>
<ol>
<li>
<div class="bullpen-chain-step__inning">
<span>7</span><small>inning</small>
</div>
<div class="bullpen-chain-step__body">
<header>
<span>Bridge pocket · vs LHB</span><strong>77.3</strong>
</header>
<h3 class="anchored">
Grant Anderson <small>RHP</small>
</h3>
<p>
Availability 100.0% · matchup 35.0% · planned 12 pitches
</p>
<footer>
Alternatives: Craig Yoho
</footer>
</div>
</li>
<li>
<div class="bullpen-chain-step__inning">
<span>8</span><small>inning</small>
</div>
<div class="bullpen-chain-step__body">
<header>
<span>Setup pocket · vs RHB</span><strong>82.2</strong>
</header>
<h3 class="anchored">
Craig Yoho <small>RHP</small>
</h3>
<p>
Availability 100.0% · matchup 70.0% · planned 12 pitches
</p>
<footer>
Alternatives: Grant Anderson
</footer>
</div>
</li>
<li>
<div class="bullpen-chain-step__inning">
<span>9</span><small>inning</small>
</div>
<div class="bullpen-chain-step__body">
<header>
<span>Finish pocket · vs LHB</span><strong>64.5</strong>
</header>
<h3 class="anchored">
Grant Anderson <small>RHP</small>
</h3>
<p>
Availability 72.5% · matchup 35.0% · planned 12 pitches
</p>
<footer>
Alternatives: Craig Yoho
</footer>
</div>
</li>
</ol>
</article>
</div>
<div class="method-callout">
<strong>Selector score, not probability:</strong> the displayed score transparently combines active-roster eligibility, availability, role fit, performance, handedness, and leverage. A confirmed batting order and same-day transaction check remain required before operational use.
</div>
</section>
<section class="dashboard-block">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Slate table</span>
<h2 class="anchored">
Every game, every uncertainty signal
</h2>
<p>
The live development run is shown here. Public release remains blocked until calibration and the remaining data-quality gates pass.
</p>
</div>
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Away
</th>
<th>
Home
</th>
<th>
Away win
</th>
<th>
Home win
</th>
<th>
Away runs
</th>
<th>
Home runs
</th>
<th>
Total
</th>
<th>
One-run
</th>
<th>
Extras
</th>
<th>
Model lean
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Cleveland Guardians
</td>
<td>
Tampa Bay Rays
</td>
<td>
44.7%
</td>
<td>
55.3%
</td>
<td>
3.6
</td>
<td>
3.9
</td>
<td>
7.5
</td>
<td>
38.9%
</td>
<td>
14.8%
</td>
<td>
Tampa Bay Rays
</td>
</tr>
<tr>
<td>
Arizona Diamondbacks
</td>
<td>
Washington Nationals
</td>
<td>
66.1%
</td>
<td>
33.9%
</td>
<td>
5.3
</td>
<td>
4.1
</td>
<td>
9.4
</td>
<td>
32.6%
</td>
<td>
12.4%
</td>
<td>
Arizona Diamondbacks
</td>
</tr>
<tr>
<td>
Chicago Cubs
</td>
<td>
Pittsburgh Pirates
</td>
<td>
29.1%
</td>
<td>
70.9%
</td>
<td>
4.5
</td>
<td>
6.4
</td>
<td>
10.9
</td>
<td>
28.1%
</td>
<td>
10.5%
</td>
<td>
Pittsburgh Pirates
</td>
</tr>
<tr>
<td>
Toronto Blue Jays
</td>
<td>
Boston Red Sox
</td>
<td>
40.6%
</td>
<td>
59.4%
</td>
<td>
3.2
</td>
<td>
3.8
</td>
<td>
7.0
</td>
<td>
40.2%
</td>
<td>
15.4%
</td>
<td>
Boston Red Sox
</td>
</tr>
<tr>
<td>
Atlanta Braves
</td>
<td>
Baltimore Orioles
</td>
<td>
38.1%
</td>
<td>
61.9%
</td>
<td>
4.3
</td>
<td>
5.3
</td>
<td>
9.6
</td>
<td>
33.7%
</td>
<td>
13.0%
</td>
<td>
Baltimore Orioles
</td>
</tr>
<tr>
<td>
Kansas City Royals
</td>
<td>
Detroit Tigers
</td>
<td>
35.0%
</td>
<td>
65.0%
</td>
<td>
4.3
</td>
<td>
5.5
</td>
<td>
9.8
</td>
<td>
32.3%
</td>
<td>
12.2%
</td>
<td>
Detroit Tigers
</td>
</tr>
<tr>
<td>
Los Angeles Dodgers
</td>
<td>
New York Mets
</td>
<td>
70.4%
</td>
<td>
29.6%
</td>
<td>
5.3
</td>
<td>
3.7
</td>
<td>
9.0
</td>
<td>
31.5%
</td>
<td>
12.0%
</td>
<td>
Los Angeles Dodgers
</td>
</tr>
<tr>
<td>
San Diego Padres
</td>
<td>
Miami Marlins
</td>
<td>
52.5%
</td>
<td>
47.5%
</td>
<td>
5.0
</td>
<td>
4.8
</td>
<td>
9.8
</td>
<td>
34.4%
</td>
<td>
12.9%
</td>
<td>
San Diego Padres
</td>
</tr>
<tr>
<td>
Athletics
</td>
<td>
Minnesota Twins
</td>
<td>
30.1%
</td>
<td>
69.9%
</td>
<td>
4.4
</td>
<td>
6.1
</td>
<td>
10.5
</td>
<td>
29.1%
</td>
<td>
11.0%
</td>
<td>
Minnesota Twins
</td>
</tr>
<tr>
<td>
Houston Astros
</td>
<td>
Chicago White Sox
</td>
<td>
42.2%
</td>
<td>
57.8%
</td>
<td>
5.3
</td>
<td>
6.0
</td>
<td>
11.2
</td>
<td>
31.8%
</td>
<td>
12.2%
</td>
<td>
Chicago White Sox
</td>
</tr>
<tr>
<td>
Colorado Rockies
</td>
<td>
Milwaukee Brewers
</td>
<td>
16.4%
</td>
<td>
83.6%
</td>
<td>
3.1
</td>
<td>
6.1
</td>
<td>
9.2
</td>
<td>
23.2%
</td>
<td>
8.6%
</td>
<td>
Milwaukee Brewers
</td>
</tr>
<tr>
<td>
Cincinnati Reds
</td>
<td>
St.&nbsp;Louis Cardinals
</td>
<td>
38.8%
</td>
<td>
61.2%
</td>
<td>
4.1
</td>
<td>
4.9
</td>
<td>
9.0
</td>
<td>
34.7%
</td>
<td>
13.1%
</td>
<td>
St.&nbsp;Louis Cardinals
</td>
</tr>
<tr>
<td>
Seattle Mariners
</td>
<td>
Texas Rangers
</td>
<td>
46.9%
</td>
<td>
53.1%
</td>
<td>
4.0
</td>
<td>
4.3
</td>
<td>
8.3
</td>
<td>
37.7%
</td>
<td>
13.8%
</td>
<td>
Texas Rangers
</td>
</tr>
<tr>
<td>
Los Angeles Angels
</td>
<td>
San Francisco Giants
</td>
<td>
55.2%
</td>
<td>
44.8%
</td>
<td>
4.7
</td>
<td>
4.3
</td>
<td>
8.9
</td>
<td>
35.5%
</td>
<td>
13.6%
</td>
<td>
Los Angeles Angels
</td>
</tr>
<tr>
<td>
New York Yankees
</td>
<td>
Philadelphia Phillies
</td>
<td>
42.2%
</td>
<td>
57.8%
</td>
<td>
3.3
</td>
<td>
3.8
</td>
<td>
7.0
</td>
<td>
39.7%
</td>
<td>
15.6%
</td>
<td>
Philadelphia Phillies
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="projection-model-card">
<div>
<span class="eyebrow">Model card · scheduled-game laboratory v4</span>
<h2 class="anchored">
What the live and shadow models know
</h2>
</div>
<div class="projection-model-grid">
<span><small>Included in current probabilities</small><strong>Posted-lineup wRC+, probable-starter FIP/xFIP/ERA blend and workload, active-roster bullpen quality, temperature, home field, and Monte Carlo score uncertainty</strong></span><span><small>Phase 4 shadow evaluation</small><strong>Named runners and relievers now drive innings, outs, score, lineup continuity, hooks, player advancement, steal tendency and success, pitcher hold, empirical park movement, walk-offs, and expanded player lines</strong></span><span><small>Publication gate</small><strong>Use the earliest 70% of 300-plus settled pregame forecasts for fitting, require improvement on the later 30%, archive versions, and audit misses before any public promotion</strong></span>
</div>
</section>
<section class="projection-activation">
<div class="section-heading section-heading--tight">
<span class="eyebrow">From prototype to daily forecast</span>
<h2 class="anchored">
Three of four activation stages are now underway
</h2>
<p>
The scheduled slate and player simulations now feed a permanent pregame ledger. Version two adds restrained platoon, recent-form, probable-starter, and available-reliever effects; the next work is proving those additions on future games.
</p>
</div>
<ol>
<li class="is-built">
<span>01</span>
<div>
<small>Built</small>
<h3 class="anchored">
Acquisition spine
</h3>
<p>
Incremental PBP cache, FanGraphs refreshes, weekly award checkpoints, schedule, starters, lineups, rosters, and weather.
</p>
</div>
</li>
<li class="is-built">
<span>02</span>
<div>
<small>Built in development</small>
<h3 class="anchored">
Matchup-aware simulator
</h3>
<p>
Current games run through batting-order quality, starter hand and form, hitter platoon and form, available bullpen strength, weather, park, home field, team score, hitter events, and starter strikeouts.
</p>
</div>
</li>
<li class="is-next">
<span>03</span>
<div>
<small>Shadow mode</small>
<h3 class="anchored">
Chronological calibration
</h3>
<p>
Future pregame snapshots will test score, win, home-run, hit, total-base, and strikeout probabilities before any public promotion.
</p>
</div>
</li>
<li>
<span>04</span>
<div>
<small>Publication</small>
<h3 class="anchored">
Automated approved board
</h3>
<p>
Only model versions that repeat their advantage on clean live forecasts can replace development probabilities or supply newsletter excerpts.
</p>
</div>
</li>
</ol>
</section>
<div class="method-callout">
<strong>Interpretation boundary:</strong> these are today’s scheduled matchups and real Monte Carlo outputs, but the probability model is still uncalibrated. Treat the page as a research prototype, not betting advice or a public forecast.
</div>
<div class="section-heading">
<p><span class="eyebrow">Build path</span></p>
<section id="what-the-current-development-model-uses" class="level2">
<h2 class="anchored" data-anchor-id="what-the-current-development-model-uses">What the current development model uses</h2>
<p>Each refresh rebuilds the slate from posted information. The current version blends batting-order quality, starter handedness, platoon results, recent form, probable-starter run estimators, active-reliever quality and workload, park, weather, and home field before drawing game outcomes.</p>
</section>
</div>
<div class="roadmap-grid">
<div class="roadmap-card is-complete">
<p><span class="roadmap-step">01</span></p>
<section id="score-distribution-layer" class="level2">
<h2 class="anchored" data-anchor-id="score-distribution-layer">Score distribution layer</h2>
<p>Complete-game draws, win splits, score intervals, close-game likelihood, and reproducible seeds.</p>
</section>
</div>
<div class="roadmap-card is-active">
<p><span class="roadmap-step">02</span></p>
<section id="matchup-aware-inputs" class="level2">
<h2 class="anchored" data-anchor-id="matchup-aware-inputs">Matchup-aware inputs</h2>
<p>BaseballR schedule, probable starters, posted batting orders, active rosters, park coordinates, and Open-Meteo game windows populate the daily contract. Posted hitters now receive restrained platoon and recent-form adjustments.</p>
</section>
</div>
<div class="roadmap-card is-complete">
<p><span class="roadmap-step">03</span></p>
<section id="named-reliever-and-runner-state" class="level2">
<h2 class="anchored" data-anchor-id="named-reliever-and-runner-state">Named-reliever and runner state</h2>
<p>The engine carries named runners and relievers through innings, outs, score, batting-order continuity, workload hooks, double plays, productive outs, steals, walk-offs, extra innings, and expanded player counting stats.</p>
</section>
</div>
<div class="roadmap-card is-active">
<p><span class="roadmap-step">04</span></p>
<section id="empirical-baserunning-and-calibration" class="level2">
<h2 class="anchored" data-anchor-id="empirical-baserunning-and-calibration">Empirical baserunning and calibration</h2>
<p>Phase 4 learns runner advancement, steal tendency, steal success, pitcher hold, and venue movement from completed games. Every input is league-shrunk and remains in shadow mode while rolling backtests, model-version tracking, misses review, and the projection archive accumulate.</p>
</section>
</div>
</div>
<div class="method-callout">
<p>These are development projections rather than betting advice. The probabilities will remain visibly labeled until repeated time-based backtests and the live pregame ledger demonstrate stable calibration.</p>
</div>
<section class="section-heading">
<span class="eyebrow">Manager decision model</span>
<h2 class="anchored">
The first bullpen-entry layer is now measurable
</h2>
<p>
The pooled hook model is evaluated on later game dates that were not used for fitting. These are development diagnostics, not production probabilities.
</p>
</section>
<div class="data-card-grid">
<article class="data-card data-card--navy">
<span class="eyebrow">Out-of-time holdout</span>
<h3 class="anchored">
Validation rows
</h3>
<div class="data-card__value">
22,386
</div>
<p>
Training through 2026-06-29
</p>
</article>
<article class="data-card data-card--red">
<span class="eyebrow">Discrimination</span>
<h3 class="anchored">
ROC AUC
</h3>
<div class="data-card__value">
0.788
</div>
<p>
Higher means pulled and retained decisions are ranked more distinctly.
</p>
</article>
<article class="data-card data-card--steel">
<span class="eyebrow">Probability error</span>
<h3 class="anchored">
Brier score
</h3>
<div class="data-card__value">
0.074
</div>
<p>
Lower is better; calibration still requires improvement before publishing forecasts.
</p>
</article>
<article class="data-card data-card--navy">
<span class="eyebrow">Observed vs predicted</span>
<h3 class="anchored">
Hook rate
</h3>
<div class="data-card__value">
8.9% / 9.1%
</div>
<p>
Observed first, mean prediction second.
</p>
</article>
</div>
<section class="section-heading">
<span class="eyebrow">Situation ladder</span>
<h2 class="anchored">
How workload changes the decision environment
</h2>
<p>
Representative tied-game contexts scored through the pooled model. These fixed scenarios isolate the shape of the model, not a specific manager.
</p>
</section>
<div class="signal-grid">
<article class="player-signal">
<div class="player-signal__top">
<span class="eyebrow">higher hook likelihood</span><span class="signal-score" aria-label="Signal score 80.2">80.2</span>
</div>
<h3 class="anchored">
Starter, deep workload
</h3>
<p class="player-signal__team">
7 inning | tied game
</p>
<p>
<strong>80.2% modeled hook probability</strong>
</p>
<p class="muted">
105 pitches | 28 batters faced
</p>
</article>
<article class="player-signal">
<div class="player-signal__top">
<span class="eyebrow">higher hook likelihood</span><span class="signal-score" aria-label="Signal score 29.1">29.1</span>
</div>
<h3 class="anchored">
Starter, third time through
</h3>
<p class="player-signal__team">
6 inning | tied game
</p>
<p>
<strong>29.1% modeled hook probability</strong>
</p>
<p class="muted">
88 pitches | 24 batters faced
</p>
</article>
<article class="player-signal">
<div class="player-signal__top">
<span class="eyebrow">middle hook likelihood</span><span class="signal-score" aria-label="Signal score 16.8">16.8</span>
</div>
<h3 class="anchored">
Reliever, first pocket
</h3>
<p class="player-signal__team">
7 inning | tied game
</p>
<p>
<strong>16.8% modeled hook probability</strong>
</p>
<p class="muted">
12 pitches | 3 batters faced
</p>
</article>
</div>
<section class="dashboard-block">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Hook scenario board</span>
<h2 class="anchored">
Starter and reliever decision points
</h2>
</div>
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Rank
</th>
<th>
Situation
</th>
<th>
Role
</th>
<th>
Inn.
</th>
<th>
Pitches
</th>
<th>
BF
</th>
<th>
TTO
</th>
<th>
Hook prob.
</th>
<th>
Relative
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
1
</td>
<td>
Starter, deep workload
</td>
<td>
starter
</td>
<td>
7
</td>
<td>
105
</td>
<td>
28
</td>
<td>
3
</td>
<td>
80.2%
</td>
<td>
higher
</td>
</tr>
<tr>
<td>
2
</td>
<td>
Starter, third time through
</td>
<td>
starter
</td>
<td>
6
</td>
<td>
88
</td>
<td>
24
</td>
<td>
3
</td>
<td>
29.1%
</td>
<td>
higher
</td>
</tr>
<tr>
<td>
3
</td>
<td>
Reliever, first pocket
</td>
<td>
reliever
</td>
<td>
7
</td>
<td>
12
</td>
<td>
3
</td>
<td>
1
</td>
<td>
16.8%
</td>
<td>
middle
</td>
</tr>
<tr>
<td>
4
</td>
<td>
Reliever, extended outing
</td>
<td>
reliever
</td>
<td>
8
</td>
<td>
30
</td>
<td>
8
</td>
<td>
1
</td>
<td>
16.6%
</td>
<td>
middle
</td>
</tr>
<tr>
<td>
5
</td>
<td>
Starter, middle innings
</td>
<td>
starter
</td>
<td>
5
</td>
<td>
72
</td>
<td>
19
</td>
<td>
2
</td>
<td>
4.8%
</td>
<td>
lower
</td>
</tr>
<tr>
<td>
6
</td>
<td>
Starter, early workload
</td>
<td>
starter
</td>
<td>
3
</td>
<td>
45
</td>
<td>
12
</td>
<td>
2
</td>
<td>
1.2%
</td>
<td>
lower
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="dashboard-block">
<div class="section-heading section-heading--tight">
<span class="eyebrow">What moves the model</span>
<h2 class="anchored">
Observed manager-decision factors
</h2>
<p>
Coefficient direction is descriptive. Correlated game situations mean these are not isolated causal effects.
</p>
</div>
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Factor
</th>
<th>
Coefficient
</th>
<th>
Association
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Workload beyond 60 pitches
</td>
<td>
2.09
</td>
<td>
Higher modeled likelihood
</td>
</tr>
<tr>
<td>
Starter role
</td>
<td>
-1.42
</td>
<td>
Lower modeled likelihood
</td>
</tr>
<tr>
<td>
Reliever role
</td>
<td>
1.37
</td>
<td>
Higher modeled likelihood
</td>
</tr>
<tr>
<td>
Batters faced beyond 18
</td>
<td>
1.19
</td>
<td>
Higher modeled likelihood
</td>
</tr>
<tr>
<td>
Adverse plate-appearance result
</td>
<td>
-0.79
</td>
<td>
Lower modeled likelihood
</td>
</tr>
<tr>
<td>
Third time through order
</td>
<td>
-0.23
</td>
<td>
Lower modeled likelihood
</td>
</tr>
<tr>
<td>
Score within two runs
</td>
<td>
0.10
</td>
<td>
Higher modeled likelihood
</td>
</tr>
<tr>
<td>
Team trailing by four-plus
</td>
<td>
-0.04
</td>
<td>
Lower modeled likelihood
</td>
</tr>
<tr>
<td>
Later inning
</td>
<td>
-0.04
</td>
<td>
Lower modeled likelihood
</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="section-heading">
<span class="eyebrow">Bullpen matchup selector</span>
<h2 class="anchored">
A Boston proof of concept for the broadcast workflow
</h2>
<p>
Left- and right-handed matchup pockets combine recent availability, pitcher role, exact MLBAM identity, handedness, and current results allowed.
</p>
</section>
<section class="dashboard-block">
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Next batter
</th>
<th>
Rank
</th>
<th>
Reliever
</th>
<th>
Throws
</th>
<th>
Role
</th>
<th>
Available
</th>
<th>
Performance
</th>
<th>
Matchup
</th>
<th>
Selector
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
L
</td>
<td>
1
</td>
<td>
Jovani Morán
</td>
<td>
L
</td>
<td>
reliever
</td>
<td>
87.2%
</td>
<td>
78.9%
</td>
<td>
100.0%
</td>
<td>
89.6
</td>
</tr>
<tr>
<td>
L
</td>
<td>
2
</td>
<td>
Alec Gamboa
</td>
<td>
L
</td>
<td>
reliever
</td>
<td>
92.2%
</td>
<td>
50.0%
</td>
<td>
100.0%
</td>
<td>
84.4
</td>
</tr>
<tr>
<td>
L
</td>
<td>
3
</td>
<td>
Ryan Watson
</td>
<td>
R
</td>
<td>
reliever
</td>
<td>
92.2%
</td>
<td>
30.5%
</td>
<td>
35.0%
</td>
<td>
66.5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
1
</td>
<td>
Jovani Morán
</td>
<td>
L
</td>
<td>
reliever
</td>
<td>
87.2%
</td>
<td>
78.9%
</td>
<td>
40.0%
</td>
<td>
77.6
</td>
</tr>
<tr>
<td>
R
</td>
<td>
2
</td>
<td>
Ryan Watson
</td>
<td>
R
</td>
<td>
reliever
</td>
<td>
92.2%
</td>
<td>
30.5%
</td>
<td>
70.0%
</td>
<td>
73.5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
3
</td>
<td>
Justin Slaten
</td>
<td>
R
</td>
<td>
reliever
</td>
<td>
89.4%
</td>
<td>
34.4%
</td>
<td>
70.0%
</td>
<td>
73.4
</td>
</tr>
</tbody>
</table>
</div>
</section>
<div class="method-callout">
<strong>Roster gate connected:</strong> candidates now must appear on the BaseballR active roster and survive the pregame workload screen. The selector remains a research lead, not a live recommendation.
</div>
<section class="dashboard-block">
<div class="section-heading section-heading--tight">
<span class="eyebrow">Calibration audit</span>
<h2 class="anchored">
Predicted probability against observed decisions
</h2>
</div>
<div class="table-scroll">
<table class="data-table">
<thead>
<tr>
<th>
Bin
</th>
<th>
Rows
</th>
<th>
Min predicted
</th>
<th>
Max predicted
</th>
<th>
Mean predicted
</th>
<th>
Observed hook rate
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
1
</td>
<td>
2,238
</td>
<td>
0.4%
</td>
<td>
0.5%
</td>
<td>
0.5%
</td>
<td>
0.8%
</td>
</tr>
<tr>
<td>
2
</td>
<td>
2,239
</td>
<td>
0.5%
</td>
<td>
1.1%
</td>
<td>
0.9%
</td>
<td>
1.5%
</td>
</tr>
<tr>
<td>
3
</td>
<td>
2,238
</td>
<td>
1.1%
</td>
<td>
1.1%
</td>
<td>
1.1%
</td>
<td>
0.3%
</td>
</tr>
<tr>
<td>
4
</td>
<td>
2,239
</td>
<td>
1.1%
</td>
<td>
1.7%
</td>
<td>
1.2%
</td>
<td>
0.6%
</td>
</tr>
<tr>
<td>
5
</td>
<td>
2,239
</td>
<td>
1.7%
</td>
<td>
7.3%
</td>
<td>
4.7%
</td>
<td>
5.0%
</td>
</tr>
<tr>
<td>
6
</td>
<td>
2,238
</td>
<td>
7.3%
</td>
<td>
8.8%
</td>
<td>
8.0%
</td>
<td>
7.3%
</td>
</tr>
<tr>
<td>
7
</td>
<td>
2,239
</td>
<td>
8.8%
</td>
<td>
14.8%
</td>
<td>
12.3%
</td>
<td>
9.6%
</td>
</tr>
<tr>
<td>
8
</td>
<td>
2,238
</td>
<td>
14.8%
</td>
<td>
16.7%
</td>
<td>
15.3%
</td>
<td>
20.0%
</td>
</tr>
<tr>
<td>
9
</td>
<td>
2,239
</td>
<td>
16.7%
</td>
<td>
17.5%
</td>
<td>
17.1%
</td>
<td>
22.1%
</td>
</tr>
<tr>
<td>
10
</td>
<td>
2,239
</td>
<td>
17.5%
</td>
<td>
98.2%
</td>
<td>
30.1%
</td>
<td>
22.0%
</td>
</tr>
</tbody>
</table>
</div>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/thesabrhood\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 The SABRhood</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="./methodology.html">
<p>Methodology</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="./glossary.html">
<p>Glossary</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="./history.html">
<p>History Desk</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://x.com/thesabrhood">
<p><span class="citation" data-cites="thesabrhood">@thesabrhood</span></p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>